### ISSUE TITLE
Nonsensical Hotkey: Ctrl+D Launches a Flare in Delve?!? (PoE Flare Hotkey = C)

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#1000]
The issue only occurs when I have POE-TradeMacro running.

C correctly launches a flare.
D correctly opens my inventory.
Ctrl+D while hovering an item correctly launches the macro price/price prediction.
**Ctrl+D while hovering nothing should open my inventory, but instead launches a flare.**

In-game shortcut keys:
![image](https://user-images.githubusercontent.com/14173022/59966250-8fe78780-94ce-11e9-9a25-6c6d2928e770.png)

Shortcut key/settings below.

![image](https://user-images.githubusercontent.com/14173022/59966226-09cb4100-94ce-11e9-901c-a79f40b0c58c.png)
![image](https://user-images.githubusercontent.com/14173022/59966232-1a7bb700-94ce-11e9-8e95-04e3000af8c5.png)
![image](https://user-images.githubusercontent.com/14173022/59966227-0df75e80-94ce-11e9-8a82-649ac04a97e7.png)
![image](https://user-images.githubusercontent.com/14173022/59966236-1f406b00-94ce-11e9-9650-f2c23afd5ea4.png)

**Comment by aRTy42** [comment]
Using Ctrl+C ingame puts a text representation of an item into the clipboard. This function comes from the PoE client itself. What the TradeMacro does when pressing Ctrl+D is sending Ctrl+C to the client and then using the item data to do the analysis and lookup.
Apparently the flare hotkey does not care that Ctrl+C was used and interprets it as just C. Since the function is from the client, I'm afraid we will not be able to change that. You will most likely need to use a different key for flares.

**Comment by dsnvwlmnt** [comment]
Oh ok, it's not a big deal, I just thought I'd report what seemed like a bug. I'm not typically hitting Ctrl+D without hovering anything.
