### ISSUE TITLE
Invalid PoE-TradeMacro Script Location

### ISSUE THREAD

**Issue by sawell1** [PoE-TradeMacro/POE-TradeMacro#1015]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version: v2.15.0
Windows version: Win 10 64 Bit
![123](https://user-images.githubusercontent.com/53223423/62014743-ee2a1900-b1a4-11e9-99d1-6ee3b92dcdb9.jpg)

Draggend the zip into:   C\Useres\name\ **OneDrive** \Documents\Poe-TradeMacro

i´ll actually don´t know why there is one drive....

Also tryied to put it into an other Drive won´t work at all...:/

Greetings from Germany :)!

**Comment by Eruyome** [comment]
OneDrive is microsofts peronal storage/cloud storage solution and putting TM there is a bad idea. It should work in other drives/folders unless it's somewhere on the desktop or in one of it's subfolders. 

I'll close this issue for now since it's quite old and the solution is "obvious", feel free to reopen it/message if you still have issues.
