### ISSUE TITLE
Some hotkeys do nothing but swap weapon sets

### ISSUE THREAD

**Issue by gregtaole** [PoE-TradeMacro/POE-TradeMacro#1018]
AHK version: 1.1.26.01
Windows version: Windows 10
PoE-TradeMacro version: 2.15.0

The script seems to be loading fine as some hotkeys are working but others don't seem to do anything but switch my weapon sets.

Working shortcuts:
- Ctrl+C
- Ctrl+I
- Ctrl+W (but still switches weapons)
- Ctrl+L
- F5
- Winkey+D

Changing the bindings does not change this behaviour.
I've also tried with a newer version of AHK both 64 and 32 bits.

**Comment by aRTy42** [comment]
What is your weapon switch key?

**Comment by gregtaole** [comment]
I've bound it to Y

**Comment by aRTy42** [comment]
I'll need to look where x is involved in the Ctrl+W command, usually it should not happen.

For confirmation: Ctrl+D and Ctrl+Alt+D both do not work?

**Comment by gregtaole** [comment]
Yes, even after rebinding the weapon swap, Ctrl+D and Ctrl+Alt+D are not working

**Comment by aRTy42** [comment]
Are you using an unusual keyboard layout?

**Comment by gregtaole** [comment]
yes, I'm using a bépo layout. I've tried switching back to azerty and qwerty but it still wasn't working.
Do I need to restart the script or the game when switching layouts ?

**Comment by aRTy42** [comment]
The script. On script launch it will read your keyboard layout, if I see this correctly it can handle the usual qwerty (and German qwertz) as well as several dvorak layouts. What the script needs are the key positions for C, V, F, A and enter. You are having the weapon swap issue with X because on a bépo layout the X key is where the c is on qwerty, so when the script tries to send a Ctrl+C command to the game (to fetch item data), it actually sends Ctrl+X in your case which has no special function and ends up being interpreted as just X, so a weapon swap.

I think detecting more layouts should be possible, I'll mention it to Eruyome. Until then you'll probably have to use qwerty if you want the script to work.

**Comment by gregtaole** [comment]
Thanks a lot for your help. I'll mark this issue closed then.
Would you be interested if I tried to make a pull request for my layout. I don't know AHK scripting so it might take a while though

**Comment by aRTy42** [comment]
The main thing I'm currently having an issue with is finding the stupid IDs for keyboard layouts. It might turn out that installing the keyboard layout and running the script function to fetch the code is the best way to get them, because I can't find any lists about them online.
