### ISSUE TITLE
keybinding conflict due to force move to QWERTY keyboard 

### ISSUE THREAD

**Issue by Mays** [PoE-TradeMacro/POE-TradeMacro#1025]
Hi,
Since this new version, my keyboard is force to move from AZERTY to QWERTY.
So the script detect keyboard conflict with "ctrl-q/w/e".
How can I solve it?

AHK version: 2.15.2
Windows version: w7

**Comment by Eruyome** [comment]
Please tell me:
- Are you using a real AZERTY keyboard or just an AZERTY keyboard layout (software)?
- Which layout are you using (keyboard language setting in windows)?
- Do you actually have conflicting keybinds or is this just a claim made by the macro because of this layout issue?

Show me:
- Your ingame keybinds, the new ones on the second skill bar (screenshot is fine).
- The `ACTION_KEYS` section of `%userprofile%\Documents\My Games\Path of Exile\production_Config.ini`. Just copy paste the text.
- Your TradeMacros assigned hotkeys. Right click the TM tray icon -> Show all assigned hotkeys -> screenshot.

**Comment by iTejo** [comment]
QWERTY keyboard. english config on windows. default settings on POE.

![image](https://user-images.githubusercontent.com/46891371/64480928-1f4d2e80-d1d2-11e9-9144-f4ca47994c44.png)

**Comment by Curlz242** [comment]
I've got the same error message. (QWERTY keyboard. Default settings on POE. Nothing changed in Macro. Never added or changed a hotkey.
![grafik](https://user-images.githubusercontent.com/40768601/64485032-39f7c580-d21b-11e9-86a7-86fad49e2090.png)

**Comment by takebo** [comment]
Same here, QWERTY keyboard. Default settings on POE.
![image](https://user-images.githubusercontent.com/5289210/64490276-c9a86e80-d231-11e9-9af3-66da7cf54373.png)

**Comment by Baenn** [comment]
Got the same issue here.

**Comment by Mesmiseim** [comment]
It is due to the new ingame keybinds for the second skill row Bound with ctrl + (Q,W,E,R,T).
Same issue here, please assign new keybinds to PoE TradeMacro.

**Comment by Mays** [comment]
Hi, thank for your quick answer.
>     * Are you using a real AZERTY keyboard or just an AZERTY keyboard layout (software)?
Real keyboard

>     * Which layout are you using (keyboard language setting in windows)?
FR
>     * Do you actually have conflicting keybinds or is this just a claim made by the macro because of this layout issue?
 Same conflict than screenshot link above.

> Show me:
>     * Your ingame keybinds, the new ones on the second skill bar (screenshot is fine).
I have not make a change of second skill bar, default setting is from bound skill 9 to skill 13, ctrl+QWERT
 
>     * The `ACTION_KEYS` section of `%userprofile%\Documents\My Games\Path of Exile\production_Config.ini`. Just copy paste the text.
I guess you need only that part:
[ACTION_KEYS]
attack_in_place=16
chat=13
close_panels=67
detonate_mines=68
enable_corpse_targeting=120
enable_key_pickup=84
generic_league_key=5
highlight=18
highlight_toggle=123
open_atlas_screen=71
open_challenges_panel=78
open_character_panel=80
open_cosmetics_inventory=75
open_events_panel=66
open_guidebook_panel=186
open_inventory_panel=73
open_ladder_panel=76
open_map=9
open_microtransaction_panel=105
open_mtx_stash=104
open_options=79
open_pantheon_panel=89
open_passive_skills_panel=221
open_social_panel=83
open_world_panel=77
performance_overlay=112
take_screenshot=119
toggle_skill_bar=17
use_bound_skill1=1
use_bound_skill10=87 2
use_bound_skill11=69 2
use_bound_skill12=82 2
use_bound_skill13=84 2
use_bound_skill2=4
use_bound_skill3=2
use_bound_skill4=65
use_bound_skill5=32
use_bound_skill6=50
use_bound_skill7=82
use_bound_skill8=6
use_bound_skill9=81 2
use_flask_in_slot1=69
use_flask_in_slot2=70
use_flask_in_slot3=51
use_flask_in_slot4=52
use_flask_in_slot5=86
use_temporary_skill1=113
use_temporary_skill2=114
weapon_swap=88
zoom_in=101
zoom_out=98

>     * Your TradeMacros assigned hotkeys. Right click the TM system tray icon -> Show all assigned hotkeys -> screenshot.
I have not made any changed of default setting.

> You can copy paste images from your clipboard here btw, no need to upload images somewhere else and link them.

May

**Comment by Eruyome** [comment]
Ok, so in general this is not an "error" but a warning. I quickly added this because PoE introduced a second skill hotbar, with some default keybindings that are clashing with the ones being used by TradeMacro.

If you don't use those new keybinds then you can simply do nothing, but TradeMacro will block those ingame keybinds from working if there are conflicts.

I won't "assign" new keybinds to TradeMacro. At least not for now. 
1. This wouldn't change the keybinds of all the thousands of people already having TM installed since an update won't change your settings.
2. These keybinds are so ingrained in my muscle memory (and that of others), and so convenient for heavily using the macro that I'm very hesitant to "just think of other good default keybinds".

For now every user will have to decide for themself whether to change the PoE or the TM keybinds and in what way. I don't think this is something critical that has to be solved immediatly for the reasons mentioned above.

**Comment by tylereaves** [comment]
I think this is a very insane default. You shouldn't block default game keybindings. Breakage sucks but the current "solution" sucks way harder. At the very, very, least this dialog should indicate clearly how to change the TM bindings.

**Comment by Eruyome** [comment]
You're right about that, but I won't rush this now for the reasons mentioned (it would only affect new users). I place value on usability, especially if I'm constantly using these keys, so I want to proplery think about new keybindings and test them to get a feel for them.

maybe I should have made it more clear on how to change the keybinds, to me it's quite obvious.

**Comment by Eruyome** [comment]
@Mays Are you one of the users reporting/complaining about the warning message or is there an actual technical issue?

Your conflicts are the same as everyones with default settings. 
Your PoE settings show the same keys being set as everyones with a non-french QWERTY layout. (Those are the decimal ASCII representations for the different keys btw).

As far as I can tell you do not have any issue besides having to change some hotkeys, either TradeMacros or Path of Exiles. Is that correct or am I misunderstanding something?

**Comment by Mays** [comment]
They was two issues in fact:
- the force move to QWERTY keyboard
- the conflict =>I try to solve it changing setting but the macro seems making my game unstable (poe crash and close if I use it many time).

**Comment by Baenn** [comment]
How can we change the macro ? Because i've try to change it via the config file and reload the script, but still got the issue... Any idea how to solve this ?

**Comment by Eruyome** [comment]
@Mays I don't get the part with "force move to QWERTY". TradeMacro does switch your keyboard layout for a very short moment when assigning hotkeys to better support all kinds of keyboard layouts ( I don't want to get into the technical details here). But this should never be something permanent.

Regarding you trying to solve the conflicts. Does it work (assigning new hotkeys)? The macro making the game unstable is extremely unlikley, are you sure the issue lies with TradeMacro, not something else?

@Baenn Don't touch the ini files, double click the system tray icon or roght click it -> Settings menu. There you have GUI fields to set/change hotkeys.

**Comment by Mays** [comment]
My keyboard stays in Qwerty, I open this ticket for that. I was thinking both issues was linked, but maybe no.
Same issue on my friend computer on windows 7 but it correctly works on another friend's pc on w10.
I played today with new hotkeys and since the latest poe patch, no crash.

**Comment by Eruyome** [comment]
@Mays I'll have to look into that, see what can be improved but it could take a bit since I don't have too much time on my hands at the moment.

**Comment by nikidino8** [comment]
Hey there, I reassigned the control key in poe but it still shows every time the warning message.

Please let us disable this warning, it's really annoying.

**Comment by Eruyome** [comment]
If you did it shouldn't appear though. If you still have this issue please show me the window.

**Comment by Mays** [comment]
Hi, thank a lot for your job, everything seems to be ok now.

Kind regards
