### ISSUE TITLE
Not able to find staffs on poe trade error and also minions deal damage if you used a skill recently also turns up an error saying it cant be found when you do an advanced pricecheck

### ISSUE THREAD

**Issue by DemonWhiteFang** [PoE-TradeMacro/POE-TradeMacro#1030]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Eruyome** [comment]
Could you ctrl + c on items that don't work and paste your clipboard contents here?

**Comment by Reloop** [comment]
I've had this issue as well with the Judgement Staff. Every single one returns a ML prediction error.
Kept them all in a stash tab i've made public now here 
https://www.pathofexile.com/character-window/get-stash-items?league=Blight&tabs=1&tabIndex=29&accountName=luciusvictus

Rarity: Rare
Doom Song
Judgement Staff
--------
Warstaff
Physical Damage: 63-117
Critical Strike Chance: 6.30%
Attacks per Second: 1.30
Weapon Range: 13
--------
Requirements:
Level: 68
Str: 76 (augmented)
Int: 76 (augmented)
--------
Sockets: B-B 
--------
Item Level: 83
--------
+18% Chance to Block Attack Damage while wielding a Staff
--------
+1 to Level of Socketed Gems
32% reduced Attribute Requirements
+38% to Global Critical Strike Multiplier
+105 to Accuracy Rating

Here's an example of one. I think the issue is with this particular staff.

**Comment by Eruyome** [comment]
That's a tricky issue, since it's a Warstaff that may be important for your search but aaparently it's not possible to search for warstaves on poe.trade at all. 
So I can only make a workaround and declare warstaves to be staves.
