### ISSUE TITLE
Questions about multi-language support

### ISSUE THREAD

**Issue by xXDarkNovaXx** [PoE-TradeMacro/POE-TradeMacro#1031]
Wouldn't it be possible to make multiple language supports when translating the items into the code?
for example: Chaosspähre = Orb of Caos
Would something like that work?
Or if you use the trading site of GGG because it supports multiple languages?
Since I can't program I just wanted to ask because I fortuitously came up with the idea

**Comment by Eruyome** [comment]
Short answer: no.

Longer Answer: it's theoretically but requires a huge effort. I already tried translating the copied item data from all client languages to english, then working with that and it worked somewhat.

But it's not enough to "work a bit", it has to work without issues. I tried using some language files used on the official trade side but they are not sufficient since their purpose is only to translate what you can find on the website, not the client side item data.  It may also be possible by using PyPoE and extracting all the language data from the Client.ggpk but that's also a big effort and I'm not sure if it works out without issues.

So unless we're getting some support from GGG on this it's just too much work/effort/hassle and I won't bother with it.

**Comment by xXDarkNovaXx** [comment]
Have you ask at GGG about support?

**Comment by xXDarkNovaXx** [comment]
> Short answer: no.
> 
> Longer Answer: it's theoretically possible but requires a huge effort. I already tried translating the copied item data from all client languages to english, then working with that and it worked somewhat.
> 
> But it's not enough to "work a bit", it has to work without issues. I tried using some language files used on the official trade side but they are not sufficient since their purpose is only to translate what you can find on the website, not the client side item data. It may also be possible by using PyPoE and extracting all the language data from the Client.ggpk but that's also a big effort and I'm not sure if it works out without issues.
> 
> So unless we're getting some support from GGG on this it's just too much work/effort/hassle and I won't bother with it.

Have you ask at GGG about support?
