### ISSUE TITLE
Exact currency option doesn't show secondary currency results

### ISSUE THREAD

**Issue by 200suranjan** [PoE-TradeMacro/POE-TradeMacro#1038]
What the title says. I price checked my 6link item and it didn't show any results. When i unchecked the exact currency option it showed the results, all of which were exalt orbs. I have exalt orb as my secondary currency.
if its working as intended i would like to suggest that u make it so that secondary currency is also included with the exact currency option.
 
Thank you for making this amazing software btw

**Comment by Eruyome** [comment]
Did you open the search on the website or did you choose the tooltip results options?

The former doesn't work since the app would have to make two separate requests after checking/noticing that the first one has no results, always opening both at the same time no matter what would be too annoying. The latter works for me because the app does make a second request when the first one didn't return any results.

Same case, 6l Loreweave in Standard, primary currency = chaos and secondary = exalts.
