### ISSUE TITLE
please support Chinese language

### ISSUE THREAD

**Issue by zqf3940** [PoE-TradeMacro/POE-TradeMacro#1049]
please support Chinese language
请求支持中文语言
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

**Comment by Eruyome** [comment]
Are you talking about supporting the chinese client or translating the apps UI (everything aside from item mods/names etc)?

Chinese client is not really possible without GGG adding more support to get translated item data instead of getting the localized data. 
The latter is also lots of work and I would need help from others somewhat fluent in those other supported languages.
