### ISSUE TITLE
Can't open TradeMacro

### ISSUE THREAD

**Issue by xGazZx** [PoE-TradeMacro/POE-TradeMacro#1075]
_TradeMacroMain.ahk

Error at line 15376.

Line Text: C:\User\xgazz\App\Local\Temp
Error:This line does not contain a recognized action.

The program will exit.

I tried to reinstall everything and still nothing.
Im asking for help.

AHK version: 1.1.32.00 (64-bit)
Windows version: 10

**Comment by Eruyome** [comment]
Properly extract the zip file. You're navigating into the zip file like it's a folder, then executing the script. Because Windows let's you do that. But that won't work.

**Comment by xGazZx** [comment]
I still dont get it. Im:
1. downloading latest version of poemacro
2. extracting the zip folder using 7zip in the same folder 
3. running Run_TradeMacro 
and outcome is always the same, "Error at line 15376"

**Comment by xGazZx** [comment]
Regardless of place where Im extracting it, there is always the same error.

**Comment by Eruyome** [comment]
`_TradeMacroMain.ahk` is a hidden file in the TM root folder. It gets created by merging some other files at run time. Please upload it here for me.

Looking at my file the mentioned line starts with
``` 
/*
	Custom macro main file. Don't delete it. Using and including this file is important. If you don't want to edit the 
	technical AdditionalMacro.txt file, you need this file and the already defined hotkey label. 
	Epsecially if you want to execute any personal code outside of hotkey labels.
	
	**TLDR**:
		You can add your own code below, use the existing Label.
		View a formatted description/how to here -> https://github.com/PoE-TradeMacro/POE-TradeMacro/wiki/Custom-Macros .

	*/

CM_ExecuteCustomMacrosCode_Label:	
	
Return
```
Which is the section where the file `%userprofile%\Documents\PoE-TradeMacro\CustomMacros\customMacros_example.txt` is being merged in.

I don't know if this is relevant. In any case the mentioned path (error message) to the `Temp` folder is not being used in the macro, any reason to it getting accessed should be for reasons like Windows having to temporarily store some files, which happens when the file is not extracted from the zip while executing the macro. Of course there may be other reasons that I'm not aware of right now.

**Comment by Eruyome** [comment]
So, did you solve it? If so, how?

**Comment by xGazZx** [comment]
I deleted all poe related files in my documents folder and after opening the script it reinstaled itself.
Everything is working properly now. Thank you for your time.
