### ISSUE TITLE
Getcookiedata.exe

### ISSUE THREAD

**Issue by jengsfp** [PoE-TradeMacro/POE-TradeMacro#162]
https://snag.gy/0FA1Jz.jpg

Kept having this error. Anyone knows how to fix it?

**Comment by Eruyome** [comment]
Have you checked if the file is actually in `\temp` folder? While compiling the script the exe is saved to the root directory and then copied to temp (maybe I can optimize this). Anyway the macro should wait until it is copied to temp and then execute it.

**Comment by Eruyome** [comment]
Please also try the new release.

**Comment by rhazor** [comment]
Not working

![123](https://cloud.githubusercontent.com/assets/22996586/21485762/ba82ec30-cbb0-11e6-8b6a-636618d95090.gif)

**Comment by budrap** [comment]
can't find this file in \temp too. how can I manually compile it?
release 1.4.1

**Comment by rhazor** [comment]
The getcookiedata.exe file is in the temp dir. It also hangs and runs in the background, have to kill via task manager.

**Comment by rhazor** [comment]
OK I made some progress by launching Internet Explorer 11 first time in 10 years and went to poe.trade and loaded the script again and this time I got this:

![1](https://cloud.githubusercontent.com/assets/22996586/21485823/fd336392-cbb1-11e6-9387-f8452073ae5f.JPG)

**Comment by Eruyome** [comment]
The macro doesn't use any browser for it's searches, it simply pretends to be one. In this case that's Internet Explorer because it's the easiest to get cookies from.

`/temp` being empty is not weird since it gets cleared on script start. 

This is how you would compile the script with the windows console:
 `[.NET InstallPath]\csc.exe /target:exe /out:[Script directory]\getCookieData.exe [Script directory]\getCookieData.cs`

This with an .ahk script (it's possible you'd have to change the path):
`RunWait %comspec% /c ""C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe" "%A_ScriptDir%\Lib\getCookieData.cs""` 
You'll get the .exe file in the script root directory, when you run the script it gets moved to /temp, you can use this to test the compiling itself though.

https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/master.zip 
You can also use this, since it has better error handling/feedback.

Have you opened the cookie file after the reading failed and checked it's content's?

**Comment by rhazor** [comment]
Yea it was missing cfclearance

**Comment by Eruyome** [comment]
Was, as in it's working now or still missing?

**Comment by rhazor** [comment]
Sorry this taking too much time debugging, I'm stick with 1.3.0

**Comment by Eruyome** [comment]
If you don't take the time you wont get a fix (possibly). Just saying.

**Comment by Eruyome** [comment]
Please check if the mentioned issues are resolved with the latest 1.5.0 release and close this issue if that's the case.

**Comment by Eruyome** [comment]
The one from your Firefox isn't "the correct one". The one from Internet Explorer is correct, too, for some reason retrieving all this information fails though. Aside from you I haven't heard any such reports so far.

Are you happy with the manual cookies or are you willing to try resolving this? Since I can't do this on my own we can close this if you don't want to ;-)

Maybe we can get @OzoneH3 or @DoctorVanGogh in here, maybe they have an idea why the .exe hangs up.

**Comment by rhazor** [comment]
It was the firewall blocking output tcp for .exe. And I can't close this issue because I didn't start it.

**Comment by Eruyome** [comment]
Oh ok, good to know.
