### ISSUE TITLE
No item found (shadowsocks proxy), slow search (China)

### ISSUE THREAD

**Issue by yinsuo** [PoE-TradeMacro/POE-TradeMacro#163]
I am a Chinese POE player. I use this trademacro search items need a lot of time, if using shadowsocks+proxifiter proxy it, press ctrl+d will display "No item found". Is there any way to speed up the search process? Because the search time really too long, about 50 seconds.

**Comment by Eruyome** [comment]
I have honestly no idea, how long does a normal request to poe.trade take for you?

**Comment by yinsuo** [comment]
I use my browser search took about 15 seconds, so up to 20 seconds the best

**Comment by Eruyome** [comment]
Btw, do you always get "no items found" or do you sometimes have results and the slow search is a seperate issue?

**Comment by yinsuo** [comment]
No item found appears after the use of shadowsock, otherwise it will slow search

**Comment by Eruyome** [comment]
Maybe I can test shadowsocks myself and find the problem, no promises though, I'm not that knowledgeable with all that networking stuff (especially proxies). Regarding the speed, I still couldn't get around implementing gzip compression for the request to poe.trade, maybe that can help.

**Comment by yinsuo** [comment]
@Eruyome think you very much

**Comment by Eruyome** [comment]
Late answer but maybe it helps. It may be possible to implement something to detect proxies to use but for now I don't have enough knowledge about this (and time). But maybe you can work something out using the [WinHTTP Proxy Configuration Tool](https://msdn.microsoft.com/en-us/library/windows/desktop/ms761351(v=vs.85).aspx). TradeMacro is using WinHTTP, a quick google search for ["shadowsocks winhttp"](https://www.google.de/search?q=shadowsocks&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=-S9sWJHxIPSv8we6q4q4CA#safe=off&q=shadowsocks+winhttp) didin't help much, especially since most results are chinese.

**Comment by Eruyome** [comment]
I will close this until I get further feedback.
