### ISSUE TITLE
[Suggestion] my own macros

### ISSUE THREAD

**Issue by Xebtria** [PoE-TradeMacro/POE-TradeMacro#174]
I have a bunch of personal macros I want to have. I am aware of the "additionalmacros.txt" file, yet this file as well gets overwritten every time I update the whole thing. 

would it be possible to create a link to a file which is taken "if it exists", and ignored if it doesn't?

that way I could keep my macros in that file and update the trade macro without having to copy/paste my macros again in that "additionalmacros.txt" each time I update...

Thanks
xeb

**Comment by jn64** [comment]
Delete the file from the *new* version you downloaded, and copy-paste the contents of the folder rather than the folder itself. That way you don't overwrite your existing file.

**Comment by Eruyome** [comment]
I didn't have the time (for example because of poe.trade cloudflare protection), but I want to write an auto updater. Ini files and additional macros would be moved to user/documents and every update would check if there's a need to overwrite those files by comparing a hash (created and saved at last file update) with the new file (current update). You could change those files but the script would still know if there were changes between releases to those files. Then just create a backup of those files and copy the new ones over (if neccessary). In most cases an update wouldn't change anything. The main script directory would simply be removed and the downloaded .zip extracted.

Of course your suggestion could be implemented though. But it would be easier to do this when those other files are moved to documents, maybe by creating a folder "own_macros" and including all files found in this folder.

**Comment by Xebtria** [comment]
The last suggestion (with that own_macros folder) would be perfect. Of course it is just a QoL feature and thus no high priority, but I'm still looking forward to the date it happens :) thanks for your work

**Comment by Eruyome** [comment]
While this folder for custom macros could still be implemented I don't think it's really necessary anymore. AdditionalMacros.txt gets not overwritten anymore aside from very rare cases where the default file was changed in an update, your file will be backed up then and you will get notified.

I will consider to do it anyway, not sure yet.
