### ISSUE TITLE
weapon spell damage math

### ISSUE THREAD

**Issue by gablona** [PoE-TradeMacro/POE-TradeMacro#224]
its adding in the WED roll to spell damage.
![wed](https://cloud.githubusercontent.com/assets/25397290/22393629/4bb02fac-e4bf-11e6-82a7-9eb253e644c8.png)

**Comment by 4GForce** [comment]
So many damage affixes, but you're right the pseudos aren't calculated properly.
If you could please copy/paste the item here that would really help us run some test with it.

( ctrl+c the item while in-game then ctrl+v it here )

**Comment by gablona** [comment]
Rarity: Rare
Dire Call
Demon's Horn
--------
Wand
Physical Damage: 26-48
Critical Strike Chance: 8.00%
Attacks per Second: 1.20
--------
Requirements:
Level: 56
Int: 179
--------
Sockets: B-B 
--------
Item Level: 80
--------
35% increased Spell Damage
--------
30% increased Spell Damage
35% increased Elemental Damage with Weapons
26% increased Lightning Damage
10% increased Mana Regeneration Rate
+11 Life gained on Kill

thanks for everything u guys do

**Comment by 4GForce** [comment]
I finally managed to get the right pseudos on my Two-Handed Dildo !

I'll commit the changes in a bit, still have some code cleaning to do.

Let me know if you think something is wrong in the calculated pseudos below.

```
Rarity: Rare
Nuclear Dildo
Affix Galore
--------
Two Handed Mace
Physical Damage: 1-999
Critical Strike Chance: 99.99%
Attacks per Second: 2
Weapon Range: 12
--------
Requirements:
Level: 69
Str: 200
Dex: 200
Int: 200
--------
Sockets: W-W-W-W-W-W
--------
Item Level: 80
--------
35% increased Spell Damage
--------
Adds 4 to 94 Lightning Damage
31% increased maximum Life
30% increased Spell Damage
35% increased Elemental Damage with Weapons
20% increased Lightning Damage
3% increased Lightning Damage with Weapons
+44% to Lightning Resistance
+41% to all Elemental Resistances
-17% to Lightning Resistance
+5% to maximum Lightning Resistance
```

![proper_pseudos](https://cloud.githubusercontent.com/assets/25257792/22406806/8ec81552-e627-11e6-890a-5c40b1bdd5bc.jpg)

**Comment by Eruyome** [comment]
```
65% Spell Damage
58% Lightning Damage with Weapons (3% inc Ligh Dmg w. Weapons + 35% inc Ele Dmg w. Weapons + 20 % Lighting Damage)
```

Spell Damage is missing.
Adding Lightning Damage to Damage with Weapons is probably right, isn't it?

**Comment by 4GForce** [comment]
You're right, spell damage was a typo I made but I was really missing the lightning damage.

I was also wondering what other pseudos we should handle ?
- mana, energy shield, accuracy rating, global crit stats, rarity item found ????????????

**Comment by Eruyome** [comment]
You're right, don't know why I didn't think of those...
Flat ES, crit chance/multi, rarity, quantity, mana. Anything else? Are there items with more than one accuracy rating mod (implicit + explicit)?
A total attributes pseudo mod would be possibel (like total resists) but this would need some more changes because it requires multiple mod groups and so far the macro supports only one mod group (at least I think so). This is also something that would be required to make jewel pseudo mods.

**Comment by 4GForce** [comment]
Well I found that Accuracy Rating can be prefix and suffix on 2 handed-swords
http://pathofexile.gamepedia.com/List_of_two-handed_sword_modifiers

Well total attribute should be easy enough, I'll see what I can do.  But while we're on attributes, I saw that when splitting combined attributes in ModStringToObject(), its trying to look for mods like '+x to Strength and Dexterity' ... does it even exist, I couldn't find any example anywhere and the regex is actually picking up strings like '+x to level of socketed Strength gems' and converting it to '+x to Strength'.

**Comment by Eruyome** [comment]
Amulets (implicit) can have 2 attributes. It seems that regex is a bit lacking though.

**Comment by 4GForce** [comment]
Total attributes, this will require more testing but it should also calculate stuff like '+x % to Strength'

![totalattributepseudo](https://cloud.githubusercontent.com/assets/25257792/22444256/32381f00-e710-11e6-95b9-f91977f61b1a.jpg)

**Comment by Eruyome** [comment]
Yeah but how is this total attributes added to the request, did you create a seperate mod group for it or simply make a single mod?

**Comment by 4GForce** [comment]
I'll look into the TradeMacro part later, for now I'm focusing on properly calculating the mods.

**Comment by Eruyome** [comment]
Sure, just want to mention it because it won't work by just creating that total attributes mod.

**Comment by 4GForce** [comment]
Maybe I should've looked at that earlier but I made a list of pseudos from the search tool on poe.trade
Note that poe.trade only has 6 pseudo but also 50 total mods ( not sure how this affects the request )

Not sure where to store that file, maybe creating a developer folder on the repo to store infos like that ?

```
[total] mods
# Life Regenerated per second
#% increased Attack Speed
#% increased Burning Damage
#% increased Cast Speed
#% increased Cold Damage with Weapons
#% increased Cold Spell Damage
#% increased Critical Strike Chance for Spells
#% increased Elemental Damage with Weapons
#% increased Fire Area Damage
#% increased Fire Damage with Weapons
#% increased Fire Spell Damage
#% increased Global Critical Strike Chance
#% increased Lightning Damage with Weapons
#% increased Lightning Spell Damage
#% increased Mana Regeneration Rate
#% increased maximum Energy Shield
#% increased Physical Damage
#% increased Rarity of items found
#% increased Spell Damage
#% of Physical Attack Damage Leeched as Life
+# to all Attributes
+# to Dexterity
+# to Intelligence
+# to Level of Socketed Aura Gems
+# to Level of Socketed Bow Gems
+# to Level of Socketed Chaos Gems
+# to Level of Socketed Cold Gems
+# to Level of Socketed Elemental Gems
+# to Level of Socketed Fire Gems
+# to Level of Socketed Lightning Gems
+# to Level of Socketed Melee Gems
+# to Level of Socketed Minion Gems
+# to Level of Socketed Movement Gems
+# to Level of Socketed Spell Gems
+# to Level of Socketed Strength Gems
+# to Level of Socketed Vaal Gems
+# to maximum Energy Shield
+# to maximum Life
+# to maximum Mana
+# to Strength
+#% to all Elemental Resistances
+#% to Cold Resistance
+#% to Fire Resistance
+#% to Global Critical Strike Multiplier
+#% to Lightning Resistance
Adds # Damage to Attacks
Adds # Damage to Spells
Adds # Elemental Damage to Attacks
Adds # Elemental Damage to Spells
Adds # Fire Damage to Attacks
Adds # Physical Damage to Attacks

[pseudo] mods
# Armour + Evasion
# Crits per second
# Elemental Resistances
# Resistances
+#% total Elemental Resistance
+#% total Resistance

```

![poe_trade_pseudos](https://cloud.githubusercontent.com/assets/25257792/22448293/737ee8ca-e726-11e6-9777-bdfd681bfc55.jpg)

**Comment by 4GForce** [comment]
Well, I didn't feel like digging too deep in the poe.trade request tonight but maybe this is why I get 'mod not found on poe.trade' message shown below.
' +#% to Lightning Resistance' is not a pseudo its a total mod & the string is not properly formed ...

![mods_not_found_on_poe_trade](https://cloud.githubusercontent.com/assets/25257792/22449175/88c568ca-e72c-11e6-8bec-e8449910fe42.jpg)

**Comment by Eruyome** [comment]
Well, that file more or less exists.. https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/data_trade/mods.json, it's just a bit bad if you want to use it as a reference unless you use some json viewer like this for example http://www.sunjw.us/jstoolnpp/.

**Comment by 4GForce** [comment]
Interesting, that's a good reference, but how did you get that file ... i mean whats the http request / link  to get it ?
I'm pretty sure it can be viewed in any browser.

**Comment by Eruyome** [comment]
IF your browser has json formatiing you can view it of course with this link https://raw.githubusercontent.com/PoE-TradeMacro/POE-TradeMacro/master/data_trade/mods.json. That file is created by scraping poe.trade with my messy nodeJS scrapers https://github.com/Eruyome/scrapeVariableUniqueItems

**Comment by 4GForce** [comment]
I need your advice, from what I think we should calculate the pseudos the same way poe.trade does, but I find it weird that in this case, Energy Shield from Intelligence (4.8%) is not calculated and the % increased Energy Shield is not added to the flat value ( 34 * (1 + 16%)) ??
What do you think ?  Stick to their method ?

![poe_trade_pseudo_calculation](https://cloud.githubusercontent.com/assets/25257792/22481801/86b9a94a-e7c4-11e6-9540-d7ad878c49d9.jpg)

**Comment by Eruyome** [comment]
Stick to their method, otherwise you won't find comparable items when using this pseudo mod. You can't calculate a total ES by using the flat and % ES since increased ES is global. Calculating this would imply "I get X total flat ES using this amulet" but in reality you would gain a lot more because of Intelligence bonus and all the other global increased ES.

**Comment by 4GForce** [comment]
I need your advice again, 1st impression, any comment ???
- Note that I added a parameter to the function to return all mods so Item Info doesn't display fire resist and cold resist because they are <= all resist base mod.

![before_and_after_montage_01](https://cloud.githubusercontent.com/assets/25257792/22489788/7d7e3fbc-e7e7-11e6-8afe-4f70bc3b843b.png)

**Comment by Eruyome** [comment]
It does show the correct value, poe.trade (and TradeMacro) don't use the range but the average ( 1 + 5 / 2 = 3), using the 10% to add/subtract from this value we have 2 and 3 as min/max.

**Comment by 4GForce** [comment]
Cold and fire resist are inherited from all resist and are not part of the base item mods, any inherited mod are considered pseudo/total by poe.trade so I was using this as a guideline.
Makes more sense to me to show the base item mods on top + the searches are different base mod/ total mod, you might not find the same results.
And, in the current TradeMacro, you would select Fire Resist thinking you're doing a base mod search but in the results you can see the query was sent looking for a total mod. (not expected results)
I mean, it would be less confusion for the users ( and for me ), but in the end, I asked on your advice because you played POE way more than I did and you been working on that script longer than I did, so you got the final saying on this. 

![search_by_total_mod](https://cloud.githubusercontent.com/assets/25257792/22522310/1b9057e8-e889-11e6-8699-b97f1233bcca.jpg)

**Comment by Eruyome** [comment]
To be honest, I don't think it really matters what mods are used on poe.trade/in the search. It's not relevant that you select a base mod and the search uses a total. When I search on poe.trade I always use totals/pseudos where it's possible no matter what my item looks like. Since we can't reliably count pre- and suffixes and include this in the search to find items with the same amount of mods it also doesn't matter how many mods are used in the search. 

Regarding the resists, I feel it's better (I prefer it this way) to seperate them and list them as seperate mods in the normal mod section, so 15 all res + 30 fire res = 15 cold/15light/45 fire. Would I search this item on poe.trade this is how I'd select the mods. Also there's more emphasis on the normal mods, so your attention should be more focused on them instead of the pseudos.

Another example, you have an item with 5 all res and 40 fire res, so you could include 45 fire res and ignore the other two (because they are so low) while including the pseudo all resist mod or even ignoring that one, too. You can do this with your changes (you have all those mods listed as pseudos) but with the old solution you save one line (2 normal + 4 pseudos vs 3 normal + 1 pseudo) and as I said already, in my opinion only mods that are in some way derived from other mods should be listed as pseudos (adding at least 2 mods together or calculating in some other way, str -> life for example).

I think we shouldn't really pay too musch attention to the way the search form/request would look like in the end as long as the search is accurate.

**Comment by Eruyome** [comment]
Btw, regarding this "Unhandled cases : mana, armour, evasion, energy shield, etc" and creating pseudomods from int/dex. Poe.trade calculates `total mana` from int, so we can add this. There's no `total/pseudo increased ES/Evasion Rating` or `total/pseudo Accuracy Rating` though. While these could be calculated and be displayed, we would have to add some flag to only use them for ItemInfo and exclude them for TradeMacro.

Poe.trade has `pseudo # to armour + evasion` but I beleive this only looks at the items defense stats to see if there is either x armour or evasion present. http://poe.trade/search/ariuniatoganoy

**Comment by Eruyome** [comment]
I made a few quick notes to your iteminfo code on your branch, was bored and wanted to do something.

**Comment by Eruyome** [comment]
Going to close this. Any other issues or discussion should be done in a new issue.
