### ISSUE TITLE
Error data (json) help

### ISSUE THREAD

**Issue by UlfMitHand** [PoE-TradeMacro/POE-TradeMacro#254]
Every time i start it up i get this error. help plz

![unbenannt](https://cloud.githubusercontent.com/assets/26175495/23572541/fcf8cba4-006f-11e7-8461-7ab7fff13123.png)

**Comment by Neph0** [comment]
Same here, with 2.0.1

**Comment by tgavankar** [comment]
+1, here too for 2.0.0 and 2.0.1.

If it helps, I do NOT have AHK installed and I'm using the Fallback.exe. This worked in older versions (1.7.x and below)

**Comment by copy0660** [comment]
I fixed my JSON error pretty easily. The problem comes from the jsonData.ahk file that fails to download a specific info from the pathofexile api(not much of a programmer, but that's how i think it works). I did it manually and i managed to launch the program. Here it is how i did it:

1. Open http://api.pathofexile.com/leagues?type=main and select all the text.
2. Ctrl+c (Copy it)
3. Go to your PoE Trade Macro folder, where the main exe (Fallback.exe) is. For example: D:\Downloads\Programs\POE-TradeMacro-2.0.1
4. Create a new folder named "temp". Make sure it's named exactly like this!
5. Go into the "temp" folder and create a new text document.
6. Open the document and paste the text that you copied from the link in the first step.
7. Save the file with the name "currentLeagues" and also change the file extension from ".txt" to ".json"
8. Run the Fallback.exe and it should be all fine.

**Comment by Eruyome** [comment]
1. Don't run the Fallback exe unless you really have to. Use `Run_TradeMacro.ahk`.
2. Running that exe skips deleting the temp folder on script start (I believe) so that solution could actually work.
3. This download uses `UrlDownloadToFile` which should only fail when Internet Explorer is not installed or some proxies are blocking it. So it more or less shouldn't fail. I can try to implement a more robust solution.

Please use the script normally and check for me if the file `currentLeagues` exists in temp folder and tell me it's contents.

**Comment by ndox138** [comment]
any fix for that???? yesterday i made the eruyome advice and it works, but now after 2.02 this error back to ocours. i try to delete and intall again and now im getting this error even with the eruyome advice :(

**Comment by Eruyome** [comment]
Unless you want to price check relic items use 2.0.1 then. Will have to see why is causing this. Are you all on Win10?

**Comment by ndox138** [comment]
yep, win 10 64b. how i can get the 2.01 version?

**Comment by Eruyome** [comment]
github sucks and doesn't list it on the release page so https://github.com/POE-TradeMacro/POE-TradeMacro/releases/tag/2.0.1.

Btw, try not saving the folder somewhere in you windows user folder.

**Comment by ndox138** [comment]
nice, i was using "documents" place to save the files, now i just put on c:and its working perfectly even without make the txt thing.   thank you!

**Comment by Songworks** [comment]
Thanks. I had the same issue since 2.0.0, also on Windows 10 64bit.
Moving the entire directory from *Documents* to *Program Files* "solved" it. :)

**Comment by Eruyome** [comment]
Could you guys run it again from documents folder after editing `resources\ahk\jsonData.ahk` and adding at line 47 

```
msgbox % test
```

This should return the return value of `FileExist(A_ScriptDir "\temp\currentLeagues.json")`

This function returns the attribute string (a subset of "RASHNDOCT") of the first matching file or folder:

R = READONLY
A = ARCHIVE
S = SYSTEM
H = HIDDEN
N = NORMAL
D = DIRECTORY
O = OFFLINE
C = COMPRESSED
T = TEMPORARY

If the file has no attributes (rare), "X" is returned. If no file is found, an empty string is returned.

**Comment by ndox138** [comment]
Im at work atm, ill be back home in +- 9 hours and i can try it

2017-03-06 9:28 GMT-03:00 Eruyome <notifications@github.com>:

**Comment by Eruyome** [comment]
So far I noticed a few things:
1. Some people have this json parse error when the downloaded file is in their user folder (when the macro folder is there)
2. At least someone has an #include error for the VersionTrade.txt, also from inside the user folder.
3. All reports so far seem to be from Win10.

This could be some issue with file attributes/permissions etc

**Comment by Songworks** [comment]
Tried as asked the change to `resources\ahk\jsonData.ahk` on a fresh 2.0.2 in directory `C:\Users\Stefan\Documents\PoE-TradeMacro`, running with either `Run_TradeMacro.ahk` or `Run_TradeMacro_no_Admin_Elevation.ahk`.

I got an empty string in the message box, where, when installation put under `C:\Program Files (x86)\POE-TradeMacro`, it outputs an `A`.

One thing I noticed when it is in the under the user directory:
It appears the `\temp` directory gets removed before it gets to the point of reading out the league data. When running `Run_TradeMacro.ahk` the `\temp` folder is created before I'm asked for admin privileges but gets removed after I give them.
Same probably happens with `Run_TradeMacro_no_Admin_Elevation.ahk` but Windows Explorer can't keep up with how fast it goes down and never even displays the temp folder at all.
While with an installation under `C:\Program Files (x86)\`, the temp folder sticks around.

**Comment by UlfMitHand** [comment]
Uhm, i always started the fallback.exe

niw im starting the trademacro.ahk and its fine

**Comment by tgavankar** [comment]
- I'm using Win7 x64.
- I've unzipped to (and am using the executable from) my Desktop directory.
- I have to use fallback.exe because AHK causes instability (crashes) in my system for unknown reasons (not related to poe-trademacro).
- Following copy0660's advice for 2.0.1 fixed the issue for me. I have not updated past that.

**Comment by Eruyome** [comment]
@Songworks I've changed the head of the `Run_TradeMacro.ahk` file to this:

```
FileRemoveDir, %A_ScriptDir%\temp, 1
FileCreateDir, %A_ScriptDir%\temp

StringTrimLeft, pathNoDrive, A_ScriptDir, 3
userFolder	:= "Users\" A_UserName "\"
isInUserFolder := InStr(pathNoDrive, userFolder)

While !FileExist(A_ScriptDir "\temp") {
	Sleep, 100
	FileCreateDir, %A_ScriptDir%\temp
	If (ErrorLevel) {		
		msg := "Directory " A_ScriptDir "\temp could not be created.`n`n"
		msg .= isInUserFolder ? "It seems you're running the script from inside your windows user folder. Windows asking you for admin privileges can interfere with the script.`n`n" : ""
		msg .= "You can try again a few times (confirm admin privileges if asked) OR move the script location to somewhere else on your pc, for example " A_ProgramFiles "."
		
		MsgBox, 5, PoE-TradeMacro, % msg
		IfMsgBox, Cancel
		{
			SplashTextOn, , 20, PoE-TradeMacro, Exiting script...
			Sleep, 2000
			SplashTextOff
			ExitApp
		}
	}
}

#Include, %A_ScriptDir%\resources\VersionTrade.txt

```

Could you check if those checks trigger when you start from inside the user folder and if it helps to retry?

**Comment by Songworks** [comment]
No. On clean install, I get no additional messages beyond the issues error. :(
Right-click and *run as administrator* has same result.

**Comment by Eruyome** [comment]
Is that a reliable fix?

**Comment by Songworks** [comment]
Yes!
I made a clean installation into another directory `\Documents\trademacro` and it works.
I guess the problem happens when both the installation and the user settings are in the same directory `\Documents\PoE-TradeMacro` and subsequently use the same path for temp. Which in turn is deleted by the user settings scripts before the league info attempts to write to it.

**Comment by Eruyome** [comment]
Ohhhh... man I didn't even notice that you (and maybe some more people) are using the same directory for both.... Of course this shouldn't be the case.

**Comment by armed109106** [comment]
Hello , how to fix , not understun , im delete all files from my doc and from C - but after reinstall still not wroked : will new fixed version ? dont know how to fix

**Comment by aRTy42** [comment]
@armed109106 What exactly is your error?
