### ISSUE TITLE
Parsing the League Data (json) from the PoE API failed.

### ISSUE THREAD

**Issue by MaysLanding** [PoE-TradeMacro/POE-TradeMacro#269]
How do I fix this?

I can't open the fallback.exe to change any options?

**Comment by Eruyome** [comment]
1. Don't use it. Use ``Run_TradeMacro.ahk`
2. Update your AHK
3. Make sure your Script folder is not set to read only (or files in it)
4. Wait a bit because I have some fixes almost ready for a release that could solce your problems.
5. https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip use the dev version but remove it again even if it works (it won't detect the upcomiing 2.0.3 version)

**Comment by MaysLanding** [comment]
So this will allow me to change search parameters?

**Comment by Zarremgregarrok** [comment]
Same issue since I updated to 2.0.1 With any version 2.0.0+

**Comment by Zarremgregarrok** [comment]
I see, 2.0.5 is working.
Good job with the error message that tells me to move install to different directory than the settings.

**Comment by Eruyome** [comment]
Took me a while to figure out this was one of the problems people had. I kind fo didn't think someone would try to mix the program install folder with the program settings folder since it's pretty common for software to use user files/app data in different locations somewhere in the user profile....

**Comment by Zarremgregarrok** [comment]
How this happened for me:
I download a zip file.
I extract a zip file to folder (of the same name as the zip file) into MyDocuments.
Last version creates a folder with pretty much the same name, but without the version suffix, right next to the the extracted folder.
I merge the folders since I think it is stupid to have two nigh-identical folders next to each other.
Bug generated.

**Comment by Eruyome** [comment]
Ok, that makes a bit of sense, although I wouldn't expect people to use MyDocuments to save such zip files/extract such software.
