### ISSUE TITLE
updater updates the wrong folder

### ISSUE THREAD

**Issue by Xebtria** [PoE-TradeMacro/POE-TradeMacro#282]
I start poe and the trade macro with a batch file. 

The batch file runs:
- a shorcut (lnk file) to the ahk file
- a shortcut (lnk file) to something else (irrelevant, just mentioning it for the sake of it)
- a shortcut to the steam app for poe.

now the shortcut for the trademacro is for this file
..\1_TradeMacro\Run_TradeMacro.ahk
I have put the trade macro into that folder because I have several more stuff in that main folder, which is labeled "2_..." "3_..." etc, it's just the way I organize stuff.

now it checks on start and tells me "hey you, there is an update available" and I update. but **instead of updating** the files in ..\1_TradeMacro\ it **creates a new folder** "..\POE-TradeMacro\" and puts the new stuff here. 

Now I don't see that directly, as I don't have the folders open all the time (I just checked today because I was wondering why it is asking again to update, as I just had updated yesterday to 2.0.6). anyways, the result is... next time I'm starting PoE via my batchfile, it again runs this file "..\1_TradeMacro\Run_TradeMacro.ahk"  ... and as a result it again asks me to update (as the files in this folder are still the 2.0.5 files.

can you please change the auto updater so it updates the files in whatever folder it was started from (in my case ..\1_TradeMacro\)  and doesn't create a new folder and screw with my folder structure? thanks.

**Comment by Eruyome** [comment]
The updater lets you choose the location and uses a default one if you don't select one yourself. Maybe there's an issue with the default one since it should be the current script directory, but unless this is fixed you should be able to select the right one.

**Comment by Xebtria** [comment]
Huh. I don't really understand why you want to stick with the POE-TradeMacro folder, but ok, it is as it is. 

I switched to the suggested "1_TradeMacro\PoE-TradeMacro" folder structure for now, as long as it works I think I can live with it. one folder level deeper won't kill me :D

**Comment by Eruyome** [comment]
One of the reasons was that this was introduced when a lot of people where already using the macro. Many of those people use a folder for every version (version suffix).
Let's say user A uses the folder 2.0.0 (manual download since this version is the first with the autoupdater), hes saves it to `PoE-TradeMacro-2.0.0`. Now he uses the updater to download 2.0.1, then later 2.0.2 and all of them go into folder `PoE-TradeMacro-2.0.0` because the script dir is used as location. Now this may not be a problem but it's not "clean" and I'm absolutely sure that there are users that get confused along the way and bother me with questions and issues.

**Comment by Eruyome** [comment]
Will close it for now.
