### ISSUE TITLE
trade searches don't put in any mods

### ISSUE THREAD

**Issue by Drachnem** [PoE-TradeMacro/POE-TradeMacro#290]
When I use the Ctrl+d it searches but doesn't put in any mods into the search.

**Comment by Drachnem** [comment]
also importing data doesn't work either seems to put in the wrong types of stats

Here is an example of the stats then what it searches (search is image attached)
Rarity: Rare
Dread Grip
Iron Ring
--------
Requirements:
Level: 57
--------
Item Level: 72
--------
Adds 1 to 4 Physical Damage to Attacks
--------
Adds 2 to 4 Physical Damage to Attacks
Adds 5 to 12 Fire Damage to Attacks
+79 to maximum Life
+28% to Fire Resistance
+42% to Lightning Resistance
+10 Life gained on Kill
![2017-03-18_17-42-12](https://cloud.githubusercontent.com/assets/26511413/24076242/4bd12b2a-0c02-11e7-8343-080fa22face9.png)
https://guides.github.com/features/mastering-markdown/

**Comment by Eruyome** [comment]
In my opinion you're contradicting yourself.

1 You say you're using ctrl + d (never considers mods) but it seems you're using ctrl + alt +d (advanced search).
2. What exactly do you mean with "importing data"? `Adds 2 to 4 Physical Damage to Attacks` becoming `Adds 5.5 Physical Damage to Attacks`? That would be correct since poe.trade uses the average of the `2 to 4` range.

I don't see any issue here.

**Comment by Drachnem** [comment]
So when I try to run Ctrl+D on items it tries to show value, but it shows base items, if I open a search with that, it doesn't load mods. If I do ctrl+C and import it does load mods but I have to scrub out like half of them for the search to work. Talking to some folks seems like the Ctrl+D is only meant for legendary items right now...

**Comment by Eruyome** [comment]
The tooltip clearly tells you it doesn't consider mod rolls. That's not some kind of error reporting but a notice for you.

Use ctrl + alt +d.
