### ISSUE TITLE
no Admin elevation is gone

### ISSUE THREAD

**Issue by noraj1337** [PoE-TradeMacro/POE-TradeMacro#314]
Why since version 2.0.7 there is no more `Run_TradeMacro_no_Admin_Elevation.ahk`?

Version 2.0.6 was the last version that had `Run_TradeMacro_no_Admin_Elevation.ahk` and `Run_ItemInfo.ahk`.

Is it a bug? I'd love to run trade-macro without admin elevation.

**Comment by Eruyome** [comment]
Because I think it's absolutely unnecessary. The only reason not to use it is not trusting me/the script. It creates more work since I have to update it if changes are made to the default launcher and leaves the possiblity to cause issues by not having the elevation, what in return causes more work for me trying to solve them.

**Comment by noraj1337** [comment]
Why trusting you? I don't know you and nobody did a code review.
This is not the only reason, maybe some people are not Administrator on the PC they are playing.
And it's always better for security not to run software with admin rights.

This is more work? May I or some people help you?

**Comment by Eruyome** [comment]
You can just decide not to use this macro then. I don't need admin rights to screw some things up if I wanted to, especially since I can still run other scripts (cmdlet, powershell etc) with admin elevation even while not using the no elevation run script. And you wouldn't ever know unless you check the code.

If someone is no administrator this shouldn't be any issue, too. Aside from that, the code is open source, while there is no "official" code review there are quite some people who checked the code for themselves and I never saw anyone anywhere having any complaints.

It is more work, help is always appreciated but in this case I don't really see the point.
I'm not one to be too stubborn but am I really wrong here with my argumentation?

**Comment by dein0s** [comment]
Well, it's always better to have a choice (from user's pov). 
But at this point we also getting a problem of maintenance. If @noraj1337 is ready to take the responsibility for it - you can give it a try, right?

**Comment by Eruyome** [comment]
I just added the commandline option https://github.com/PoE-TradeMacro/POE-TradeMacro/commit/3359613eb2b98eebc1b74f92b931a9b69c6df3ea and made a short how to on the FAQ page.

**Comment by noraj1337** [comment]
@Eruyome : I didn't want to offend you. Thanks for the commit. It's a perfect compromise. Thank you.
I'll try it in the next release.
As a security POV it's always better not to ask elevation of privilege when it's not needed. A parallel could be "not using sudo or root acount on Linux to do unprivileged tasks".

**Comment by Eruyome** [comment]
I wasn't offended.

You're right but not using admin elevation is prone to leed to issues especially on Win10, with all the file copying, folder creation and so on. I'd rather force it than be bothered by a lot of users having some issues.
