### ISSUE TITLE
Crtl+F highlight items not working properly for different languages

### ISSUE THREAD

**Issue by JYshadow** [PoE-TradeMacro/POE-TradeMacro#351]
I use the dutch keyboard setting, which means that when I want to type _"example"_, I have to press spacebar between the _"_ and the _'e'_, otherwise it will become _ëxample"_. This messes up the _'crtl+f'_ feature for me. Where can I change this in my own macro (by simply adding a {space})? I guess its not required to do this for everyone. 
I hope my explanation is clear enough.

**Comment by Eruyome** [comment]
So basically you'd need a space after every opening quotation mark to make sure it works? You can't really change that at the moment without editing the `HighlightItems` function in `resources\ahk\PoE-ItemInfo.ahk`.

Not only is this not required for everyone, it would mess up the search for everyone not having the dutch layout since it would result in `" Voidbringers"` and that should cause the highlighting feature to not find anything.

**Comment by Eruyome** [comment]
A possible solution would be to have some function arguments, for example `^f::HighlighItems(false,true)`.
Tde first parameter is to use the broader terms, the second one could be to add the space that you need. Then you could edit AdditionalMacros and set this parameter true.

**Comment by Eruyome** [comment]
Btw, this only happens to the characters `eioa` and the space should only be added when the first character after the space is on of these? Are there other languages with the same issue but additional characters?

**Comment by Eruyome** [comment]
The current ItemInfo dev branch has a first version of some improvements, try it out https://github.com/aRTy42/POE-ItemInfo/archive/devEru.zip

You can change the function parameters in AdditionalMacros.

**Comment by JYshadow** [comment]
I figured it wouldn't be convenient to change it for everyone, that's why I wanted to change it in my own files, but I didn't know where or how. It only happens the characters _`eioau`_. I've tested it and the opening quotation mark now works properly, but the closing quotation mark doesn't work. I should have mentioned that every special character that can be combined with a letter ^ ' " ` ~ require a {space} after being typed to appear. Simply put: it also needs a {space} after the closing quotation mark. Then it should work properly.

**Comment by Eruyome** [comment]
So, it actuall doesn't matter if the character following a quotation mark is one of these: `eioua`?

**Comment by JYshadow** [comment]
Well, it does, If the opening quotation mark is followed by one of `aeiou` (just vowels) without typing a {space} in between, it will become `äëïöü`. So, if I want to type a quotationmark seperately, I need to press {space} after the quotationmark. 
Note: a {space} is not required when typing a consonant after a quotation mark. because those cannot be combined.

**Comment by Eruyome** [comment]
Yeah I get that with the vowels and consonants, I wanted to make sure about the closing one, some character has to be typed to make the " appear, best choice being the space, right? Tried to change my keyboard language to test it but it didn't work out.

**Comment by JYshadow** [comment]
Yes, space would be the best choice. The _US International Keyboard_  seems to have the same setting.

**Comment by Eruyome** [comment]
I don't think so, this is not just an issue with the language selected in windows. Changing to US still works for me and I would have gotten a lot of reports from US users if that where the case.

**Comment by Eruyome** [comment]
I believe it should work now https://github.com/aRTy42/POE-ItemInfo/archive/devEru.zip

**Comment by BirMa** [comment]
Additional info, for everyone that just swung by and wants a fix for this beyond AHK scripts:
- Those keys (that produce the letters: "~'`^ and therefore also äöü etc.) are called "dead keys", because the don't immediately produce a key after pressing but wait for another key.
- Since AHK only simulates key presses probably all keyboard layouts with dead keys are affected by this.
- I firmly believe this is an issue on window's side, since they refuse to get rid of this dead-key fuckery, it interrupts the flow of writing, is really annoying for programmers and breaks macros as seen here.


**How to fix that once and for all:**  
Hence I downloaded the official Microsoft tool "Keyboard Layout Creator 1.4" from [https://msdn.microsoft.com/en-us/globalization/keyboardlayouts](https://msdn.microsoft.com/en-us/globalization/keyboardlayouts) and loaded my preferred layout (us-international in my case) and right-clicked on every key that had a dead key configured.  
Saved The new Keyboard Layout  
Klicked on Project->Build DLL and setup package  
And installed the resulting keyboard layout (and set it as my new default).

**Comment by JYshadow** [comment]
Yes, it works perfectly now, thanks a lot!

**Comment by Eruyome** [comment]
So this can be closed? Or should I wait a bit until a new release was made to let people see @BirMa's comment?

**Comment by BirMa** [comment]
Suggestion for a pragmatic solution:  
In the next release: Write a line mentioning the dead-key problem and the Windows Layout Creator in the Changelog-section of the next release. I mean that dialog that pops up when you start POE-TradeMacro and informs you of new versions.  
I suppose that's not what that dialog is for, but it would reach the most people.  
And maybe keep the issue open until that release but give it a label like "won't fix" or "windows issue".

Also: Thanks for answering so quickly on this!

**Comment by lemasato** [comment]
Just suddenly remembered about reading this.
Why not use the clipboard? It would effectively get rid of any dead key issue.
Store the search text in the clipboard, then use CTRL+V.
Could even be used as an argument "useClipboard".

**Comment by Eruyome** [comment]
I actually haven't thought about that... you're probably right about it solving the issue.

**Comment by Eruyome** [comment]
Actually that's easier said than done.

Clipboard before using the highlight function: `Test`

Code to assign the searchText to the clipboard and paste it:

``` 
Clipboard := searchText
Msgbox % Clipboard
SendInput ^{v}
```

The Msgbox shows (for example): `"Maze Map" "Tier:14"` BUT the pasted text is `TEST`.
I tried a few things, even some delays and googled this issue but couldn't solve it yet. Maybe I'm an idiot, maybe it's actually that hard to accomplish.

**Comment by lemasato** [comment]
After some testings, it's an issue with SendInput being too fast.
```
Numpad1::
Clipboard := "BEFORE"
SendInput ^v
; Sleep 1
Clipboard := "AFTER"
Return
```
Without the 1ms Sleep, "AFTER" is being sent almost all the time, with a few very rare "BEFORE" inputs.
With the 1ms Sleep, it's the complete opposite. It works, but there are still a few rare "AFTER" inputs.

SendEvent without Sleep: Same as using SendInput with 1ms.
SendEvent with 1ms Sleep: Works flawlessly.

**Comment by Eruyome** [comment]
You're right, using SendEvent and a few timeouts seems to make it work. Since my keyboard doesn't have those vowel deadkeys I added `´` (which is a deadkey) to the string and my tests were successful. Therefore this should work for all dead keys but I'd like to have someone else test it. @JYshadow how about it?

Here's an ItemInfo dev version https://github.com/aRTy42/POE-ItemInfo/archive/devEru.zip, it always uses the clipboard, no need edit any parameters.

**Comment by JYshadow** [comment]
Test successful. No problems with the dev version.

**Comment by Eruyome** [comment]
Ok, nice.
