### ISSUE TITLE
Ctrl + D not working for unique items

### ISSUE THREAD

**Issue by Remedy4You** [PoE-TradeMacro/POE-TradeMacro#358]
Hello,   I have run into an issue where Ctrl + D is not searching for listed prices for Unique items. 
The search will take an extended amount of time and finally come out as "No Item Found."
The search works normally when using ctrl + d on any currency. 
I have attached a short clip of the trademacro settings (default) as well as what happens when I try to run a ctrl + d.  
Tried to keep it as short as possible due to the size limitations of attachments on this site. 
[2017-05-06-1606-50.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/980973/2017-05-06-1606-50.zip)

**Comment by Eruyome** [comment]
You could upload your video anywhere and link it here but it was informative enough.

There are no such reports from other people and it works for me so it shuld be on your end. I'll make a dev version of the script with some debug output that hopefully show the issue at hand.

**Comment by Eruyome** [comment]
I'm an idiot :p That debug output is there already. Please run a search and upload the file `temp\DebugSearchOutput.txt` somewhere for me. Do this once for a currency search and then for the unique/rare search.

Btw, while ctrl + d is not optimal for rare items this doesn't matter for debug purposes at all, also you can use ctrl + alt + d and then show the tooltip instead of opening it on poe.trade, this uses the same functions as ctrl + d.

**Comment by Remedy4You** [comment]
I went ahead and made a clip from start to finish. 
https://www.dropbox.com/l/scl/AABGAXwhK_FpEkb1Ytb-VsI730ozgeXk_rE

please pardon my ignorance, but it looks like there is no DebugSearchOutput file anywhere. after I run the searches the file is nowhere to be found no matter if the macro is open or closed. unless I am doing something wrong.

**Comment by Eruyome** [comment]
I mentioned that you have to use the `debug output` option in the settings menu. Bottom right above the buttons.

**Comment by Remedy4You** [comment]
[DebugSearchOutput.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/981053/DebugSearchOutput.txt)

Above is the debug output for the currency search.

When I run a search on a Unique or a Rare nothing happens to the Output file (it remains blank)
I have added a image of both the output text fire After a unique/rare search as well as the Console. 

![unique debug pic](https://cloud.githubusercontent.com/assets/28486189/25774454/1f2619e2-328f-11e7-8d05-e87db150e8d6.PNG)

**Comment by Eruyome** [comment]
The currency search uses `currency.poe.trade` while all other searches are using `poe.trade`. 
For some reason the latter isn't returning anything.

Please also run `resources\tests\Test_WinHTTPRequest.ahk` and show me the output. You can copy the output from the console instead of using screenshots.

**Comment by Remedy4You** [comment]
[consolesavedataforoutput.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/981453/consolesavedataforoutput.txt)

**Comment by Eruyome** [comment]
That looks good, even the last test which is a valid search, there shouldn't be a difference to a search done via ctrl + d. You still have those issues?

**Comment by Eruyome** [comment]
I'll close this for now, just reopen it if there still are issues.
