### ISSUE TITLE
Custom Macro on F4

### ISSUE THREAD

**Issue by babis8142** [PoE-TradeMacro/POE-TradeMacro#394]
Do you guys have reserved F4 for some purpose? I can't get a macro to trigger on F4. I do have plenty of macros all of them working just fine, most of them on F keys. The button works on the keyboard (Alt + F4 macro works) 

I do have the latest version and my macros are on the right file (custom macros directory)

**Comment by Eruyome** [comment]
Just take a look at the first section in `AdditionalMacros` where the variables are declared. 

`global AM_KickYourself		:= ["off", "F4", "Input your character name here"]`

While this is disable ("off") it probably still overrides your F4 hotkey. I haven't tested it but enabling it may work for you since your own macro reassigns the hotkey to do different things. Alternatively you can simply set some other hotkey there.

**Comment by babis8142** [comment]
ok thanks that was the issue. I changed that file to F10 (since I have nothing set to F10) and I'm good

I did see that but since it was set to off I thought it wouldn't be a problem.
