### ISSUE TITLE
google Chrome security warning & WS.Reputation.1

### ISSUE THREAD

**Issue by BudSpanker** [PoE-TradeMacro/POE-TradeMacro#395]
Hello there,

maybe you're already knowing about this, if not, I'd like to inform you about google chrome blocking access to your github downloads with a security warning. Furthermore my Antivirus software (Norton IS) automatically deleted the file "curl.exe" in the POE-TradeMacro-2.3.5-beta.2 folder.

I'll post you a few screenshots. Sorry that some are in german language, but I'm sure you'll get the meaning

Cheers and keep up this great work! :)

![zwischenablage01](https://user-images.githubusercontent.com/30430253/28560737-240119fa-711c-11e7-8abc-650897e22464.jpg)

![zwischenablage02](https://user-images.githubusercontent.com/30430253/28560766-29403194-711c-11e7-994c-3327baf12457.jpg)

![zwischenablage03](https://user-images.githubusercontent.com/30430253/28560776-30b7ab32-711c-11e7-815c-c5769ab08306.jpg)

**Comment by Eruyome** [comment]
I didn't know of this since I don't get those warnings with either firefox or chrome, I'm german myself so no issues there.

I can see why it's not impossible for some antivir software to flag that exe, not sure if I can do something about that though. cURL doesn't get distributed precompiled officially but there are some trusted sources to download precompiled versions of it. 
Main page: https://curl.haxx.se/download.html 
Version that I'm using: https://bintray.com/vszakats/generic/curl/ (curl-7.54.1-win32-mingw.7z)
