### ISSUE TITLE
Windows makes a sound whenever i press a macro

### ISSUE THREAD

**Issue by Atlapro** [PoE-TradeMacro/POE-TradeMacro#401]
Its like when ur pc has a pop up sound that kinda sound is what it makes whenever i press a macro from the script i dont know if this is normal or not? But if i mute system sounds its gone :o if any more info is needed tell me please :dagger: 

Im running the game on Widowed Full screen and also i am using an Azerty key board.
and i tried running it as an admin and normal.

**Comment by Eruyome** [comment]
That's not normal. Can you use a different macro, for example an `.ahk` file with following contents:

```
f6::SendInput {F5}
```

This would work globally, anyway, does this also make sounds?

**Comment by si0x** [comment]
I have the same problem, whenever i use a script i get the windows sound.

**Comment by Eruyome** [comment]
@si0x "A script" meaning any ahk script or meaning any trademacro hotkey?

**Comment by si0x** [comment]
any script that tries to get information from the browser i have the same problem with lutbot price check macro but not the other ones from lutbot

**Comment by Atlapro** [comment]
@Eruyome  Sorry for the late answer kinda  was traveling i tried ur script and that one doesn't make any sound so i guess its something with the macro then?

**Comment by keeb** [comment]
I'm getting the exact same thing.  I am around and watching if there's anything you want me to debug.

**Comment by keeb** [comment]
Running as administrator doesn't change anything

**Comment by Eruyome** [comment]
I'm not sure what to look out for or to debug specificially, will have to read up on that, maybe I can find something.

**Comment by si0x** [comment]
@Eruyome I think the problem is with the windows 10 creators update, i started an old version of your script where i thought that i wont get the windows sound but i got it.

**Comment by Eruyome** [comment]
Hm, I'm running 8.1, so it will be hard to work on that issue, but maybe I can read it up when it's releated to that.

**Comment by si0x** [comment]
I muted the windows warning signal sound and that fixxed it. But i dont really wanna mute the sound tho.

**Comment by JordanICollier** [comment]
Any update on this?

**Comment by Eruyome** [comment]
Not yet, was a bit busy, sry.

**Comment by Eruyome** [comment]
I don't think there's a good solution that I can implement via script, but you can disable various types of sounds. I'm not sure how good you can "fine tune" this though, especially since I don't have Win10. 
Could you just try a few things and tell me what worked best?

[google search](https://www.google.de/search?q=windows+10+disable+keypress+sound+beeps&oq=windows+10+disable+keypress+sound+beeps&gs_l=psy-ab.3...2744.2744.0.2882.1.1.0.0.0.0.80.80.1.1.0.foo%2Cnso-ehuqi%3D1%2Cnso-ehuui%3D1%2Cewh%3D0%2Cnso-mplt%3D2%2Cnso-enksa%3D0%2Cnso-enfk%3D1%2Cnso-usnt%3D1%2Cnso-qnt-npqp%3D0-1701%2Cnso-qnt-npdq%3D0-54%2Cnso-qnt-npt%3D0-1%2Cnso-qnt-ndc%3D300%2Ccspa-dspm-nm-mnp%3D0-05%2Ccspa-dspm-nm-mxp%3D0-125%2Cnso-unt-npqp%3D0-17%2Cnso-unt-npdq%3D0-54%2Cnso-unt-npt%3D0-0602%2Cnso-unt-ndc%3D300%2Ccspa-uipm-nm-mnp%3D0-007525%2Ccspa-uipm-nm-mxp%3D0-052675...0...1.1.64.psy-ab..0.0.0.pTiYwSwHF4o)

**Comment by Atlapro** [comment]
@Eruyome for some wierd reason it doesn't make the sound anymore havent changed anything yet or not that i know off so im happy but i can't really help other people :S
