### ISSUE TITLE
"ChangeLeagueHotKey" and support any keyboard layout?

### ISSUE THREAD

**Issue by Uoipka** [PoE-TradeMacro/POE-TradeMacro#426]
Some problem here. Then I change all the hotkeys in Documents\PoE-TradeMacro\config_trade.ini to Scan Codes In order to constantly not change the keyboard layout like this:
[Hotkeys]
PriceCheckHotKey =^sc20
AdvancedPriceCheckHotKey =^!sc20
OpenWikiHotKey =^sc11
CustomInputSearchHotkey =^sc17
OpenSearchOnPoeTradeHotKey =^sc10
ShowItemAgeHotKey =^sc12
ChangeLeagueHotKey =^sc26

Anyway I get errorr to (for some reason???) "ChangeLeagueHotKey" and only way to fix (for me) it is change in "PoE TradeMacro\resources\ahk\TradeMacroInit.ahk" - [https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/TradeMacroInit.ahk#L74](url)
From - ChangeLeagueHotKey := "^l"
Replace to - ChangeLeagueHotKey := "^sc26"

Well next, I need to change: "Documents\PoE-TradeMacro\AdditionalMacros.txt"

global AM_Minimize		:= ["on", "#D"]
global AM_HighlightItems	:= ["on", "^F"]
global AM_HighlightItemsAlt	:= ["on", "^!F"]
global AM_LookUpAffixes	:= ["on", "^M"]

Replace to:

global AM_Minimize		:= ["on", "#sc20"]
global AM_HighlightItems	:= ["on", "^sc21"]
global AM_HighlightItemsAlt	:= ["on", "^!sc21"]
global AM_LookUpAffixes	:= ["on", "^sc32"]

So what is this all about? 
What wrong with "ChangeLeagueHotKey" and maybe some way that it can be default or something like that? :D
btw - [https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/config/default_config_trade.ini#L37](url)
Wrong comment. Default is Ctrl + l
And here - [https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/resources/ahk/TradeMacroInit.ahk#L69](url)
Wrong/old hotkey? It is Ctrl+Alt+D default didn't it? or what is it

**Comment by Uoipka** [comment]
It's need adjustments cause sometimes it's don't catch scancode ;c

**Comment by Eruyome** [comment]
You have to walk me through this again.

Let's say you have a fresh install with default settings. Do you get any error messages when you run the macro or do your hotkeys simply not work?

Do they work not when using the settings menu to configure them? I thought that shoudl work since it uses AHKs Gui element for inputting keys/key combinations.

I guess it would be possible to translate all default hotkeys from the ini file and additionalmacros to their scan code counterparts, not sure how hard it will be to support all possible custom keys.

**Comment by Uoipka** [comment]
> Let's say you have a fresh install with default settings. Do you get any error messages when you run the macro or do your hotkeys simply not work?

On Russian keyboard layout I get 6 error mesages like this https://momo.s-ul.eu/JWt1bsTH.jpg after https://momo.s-ul.eu/002w9QWb.jpg and after last message I can't configure them in settings menu because marcos didn't load properly (white icon). It's work fine after reload script and set ENG keyboard layout even if after in game I'll using RUS keyboard layout.

If I change all hotkey to scan code in default_AdditionalMacros.txt and default_config_trade.ini (on fresh install) only error is this https://momo.s-ul.eu/kqszmPKs.jpg for some reason in config menu he is display correctly https://momo.s-ul.eu/uZy3JuZ9.jpg but didn't work in game.
After all of this and fixed last error in TradeMacroInit.ahk I don't get any error mesages on start or while playing on any keyboard layout.

**Comment by dein0s** [comment]
While I agree about the scan codes part (also wanted to create a qol issue about it cos I suffer from this by myself :D) I still can't get a point of this particular issue.

@Uoipka can you, please, describe your problem in russian step-by-step so we can finally figure out what's going on here.

p.s. Btw, looks like I've found another issue with scan codes while was digging around with this: it seems that TradeMacro completly ignore hotkeys from config_trade.ini if they were specified as a scan code value. I'd guess this is because of some problems when it tries to display it in gui. But this doesn't belong to here and not a critical thing either. If you need some more details I can create another issue or you can catch me on discord - dein0s#2248.
Example:  `ChangeLeagueHotKey =^SC01A` where `SC01A` goes for square bracket `[`.

**Comment by Eruyome** [comment]
This whole scan code stuff seems to be tricky... best case would be to have a translator and it may be easier than I thought (hopefully). 
https://autohotkey.com/docs/commands/GetKey.htm
Parsing the hotkey combination using a list of hotkeys https://autohotkey.com/docs/KeyList.htm and Symbols https://autohotkey.com/docs/Hotkeys.htm#Symbols.

**Comment by Uoipka** [comment]
> can you, please, describe your problem in russian step-by-step so we can finally figure out what's going on here.
The only problem is that I can not use RUS key. layout on start trade macro. That's it

> p.s. Btw, looks like I've found another issue with scan codes while was digging around with this: it seems that TradeMacro completly ignore hotkeys from config_trade.ini if they were specified as a scan code value. 
Try do it on default config

**Comment by Eruyome** [comment]
You should never edit the default files though, since they are replaced with every update.

**Comment by Uoipka** [comment]
> You should never edit the default files though, since they are replaced with every update.

Yes. But for now it's only way to remain scan code in config

**Comment by dein0s** [comment]
@Uoipka while there's no any public beta atm, you can try [this version](https://github.com/PoE-TradeMacro/POE-TradeMacro/tree/fff29b1402132259046aaa372959148018c5582f) (which is based on my pr https://github.com/PoE-TradeMacro/POE-TradeMacro/pull/493 on top of the current 2.5.5 release) and provide us with your feedback. Will be very appreciated.

**Comment by Uoipka** [comment]
@dein0s It's run perfectly fine. I'll try longer, but I don't think that find any bugs. thx

**Comment by dein0s** [comment]
Can you, please, also provide the following info (no sensitive data needed):
1) current os (version and architecture if possible, x86 or x64)
2) current ahk (version and architecture if possible, u32 or u64)
3) non-eng keyboard layouts that you have installed (except russian obviously)

**Comment by Uoipka** [comment]
@dein0s Win 10 x64 ver. 1703 (build 15063.540), Ahk 1.1.26.01 x64, Japanese (no problem here even on old version)

**Comment by Eruyome** [comment]
fixed in the beta releases and stable releseas later on
