### ISSUE TITLE
Cant open AHK file

### ISSUE THREAD

**Issue by WolfLF** [PoE-TradeMacro/POE-TradeMacro#432]
There is no 'run script' button when i right-click, just says 'open with' and then shows me no apps? Any help with this?

**Comment by Eruyome** [comment]
![image](https://user-images.githubusercontent.com/16058242/29282571-94a83352-8123-11e7-8d82-9f4813f487e6.png)

This is the TradeMacro folder that you should have extracted (plus some more files/folders since it's my dev version). If you have AutoHotkey installed you can simply double click `Run_TradeMacro.ahk`.
