### ISSUE TITLE
leaving global channel

### ISSUE THREAD

**Issue by Moksu** [PoE-TradeMacro/POE-TradeMacro#443]
Hey,

has anyone else found a problem when using this program it somehow leaves manually set global channel?

edit: I also got the join global channel binded to F5. No idea if someone of the extra macro's are doing something nasty in poe-trademacro? only really using it for price checking

**Comment by aRTy42** [comment]
If you are talking about trade 820 and global 820, they can be so busy that PoE doesn't connect when you switch an area. You might remember seeing a "timeout while connecting to chat" message at some point when you tried to use the chat command, to my understanding that happened because of high player load. Every time you switch between zones the client attempts to reconnect you to your previous channels, but if that fails, you effectively disconnect from them.

**Comment by Moksu** [comment]
> If you are talking about trade 820 and global 820, they can be so busy that PoE doesn't connect when you switch an area. You might remember seeing a "timeout while joining chat" message at some point when you tried to use the chat command, to my understanding that happened because of high player load. Every time you switch between zones the client attempts to reconnect you to your previous channels, but if that fails, you effectively disconnect from them.

Thanks for the info. Did not know that.. and really sorry for blaming it on this fantastic program.
