### ISSUE TITLE
Is this bannable?

### ISSUE THREAD

**Issue by martin-dimitrov13** [PoE-TradeMacro/POE-TradeMacro#445]
Title.

**Comment by Eruyome** [comment]
Short: No.

Long: Despite what you may believe the script doesn't interact with the PoE at all aside from a few hotkeys in AdditionalMacros.txt, the hotkeys that do so follow the commonly accepted rules (no memory reading, no automations, not more than one server-side action triggered per button press etc).

But nothing of that shows it more than the macro downloads since so far not a single ban was associated with TradeMacro http://www.somsubhra.com/github-release-stats/?username=poe-trademacro&repository=POE-TradeMacro.
