### ISSUE TITLE
Not working  search and other function

### ISSUE THREAD

**Issue by Xaaalera** [PoE-TradeMacro/POE-TradeMacro#489]
I can only change league  -> CTRL + L 
 And where i starting script  open    Explorer 
![image](https://user-images.githubusercontent.com/10559079/30003576-3d3c84e2-90c8-11e7-8553-f189e8aa8964.png)
 pls helping  man :) i  i dont know whot i mist doing, because my eng is very bad sorry ;(

**Comment by Eruyome** [comment]
Right click the system tray icon -> show all assigned hotkeys, this shows you a window, make a screenshot and post it here

**Comment by Xaaalera** [comment]
![image](https://user-images.githubusercontent.com/10559079/30003900-f75eb778-90cd-11e7-965a-de6a90e08aef.png)

**Comment by Eruyome** [comment]
Your hotkeys should work. They are all recognized/assigned. Are you running in windowed/borderless windowed?

**Comment by ath31st** [comment]
Hi! I have this problem too. Only ctrl+L working

**Comment by aRTy42** [comment]
Same question to you: Are you running PoE in windowed or borderless windowed? Fullscreen won't work.

**Comment by ath31st** [comment]
I am always play in window.

**Comment by pvpshoot** [comment]
Downgrade to 2.5.2 and work only ctrl+l
keyboard with russian symbols 
![image](https://user-images.githubusercontent.com/6636655/30071756-0728156c-9279-11e7-8ef4-73eb6bed0441.png)

**Comment by pvpshoot** [comment]
i still think that it connected to keyboard layout, because in the thirst screen there is russian client of the game

**Comment by dein0s** [comment]
@pvpshoot if you're talking about the screen from https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/489#issuecomment-326808608 then you're wrong.
It's nohow connected to the game client localization afaik, and he's using ENG keyboard layout (take a look at the taskbar, bottom right side). That means everything should be ok.

**Comment by pvpshoot** [comment]
First screen. Second. My. And I think your environment is Russian windows. With Russian lang. It works for none of us! Совпадение? Не думаю!

**Comment by ath31st** [comment]
pvpshoot, похоже дело в ру-клиенте игры. я даунгрейднулся до 2.5.2, но там работает только cttl+i, как ты и писал. Но этого мало, хотелось бы автопоиском пользоваться.

**Comment by pvpshoot** [comment]
Does it work for anyone in Russian client?

**Comment by Eruyome** [comment]
According to my statistics which I started collecting just a few days ago, there are at least 3,400 russian TradeMacro users. I don't know how many of them have a russian windows or even game client but in general the macro works for almost all of them.

**Comment by pvpshoot** [comment]
How can we help to debug this? Any log or something?

**Comment by Eruyome** [comment]
The macro can't work with non-english clients since the item data text has to be english.

**Comment by pvpshoot** [comment]
Oh. So bad news. Any way to use eng version on Russian servers?  Sorry can't see in game. Write from my phone

**Comment by Eruyome** [comment]
I believe you can play any language on any server. At least there are a lot of russians playing the ENG version.

**Comment by Eruyome** [comment]
![image](https://user-images.githubusercontent.com/16058242/30073269-7d8ce748-926d-11e7-983e-7ee32adc50c9.png)

This issue is mentioned quite obviously.

**Comment by dein0s** [comment]
Well, let me make a few notes on this:
- i was wrong in my previous comment about localized game client, iteminfo and trademacro depends on english localization, because otherwise it can't parse the item data (все скрипты, которые парсят информацию из клиента, завязаны на английскую локализацию)
- windows environment, keyboard layout and other stuff like this can only influence the hotkey firing, not the script functionality itself (ваша раскладка, переменные окружения и прочая могут повлиять только на триггер хоткеев, но никак не на работоспособность самого скрипта)

And yes, @pvpshoot , you can still play on Moscow gate with EN client - just click the appropriate flag in the top left corner on the login screen ![screen](https://i.imgur.com/bFTIJXm.png)
Можно играть на любом доступном гейте основного реалма (не китай) с любой локализацией игрового клиента. Переключатель в левом верхнем углу на экране логина.
А саркастические выпады можно и попридержать. Особенно в тех случаях, когда не разделяешь понятия keyboard layout и system environment от client localization.

**Comment by ath31st** [comment]
Yes, with eng lang and ru-client this macros working

**Comment by pvpshoot** [comment]
@dein0s за развернутый ответ спасибо. А предьяву насчет лейаутов чот не понял

**Comment by Xaaalera** [comment]
Ty Ctrl+I is  nice.... its wirking :D

**Comment by Xaaalera** [comment]
![image](https://user-images.githubusercontent.com/10559079/30075178-b5d145ea-927c-11e7-95b5-bf57dac8a3ca.png)
yeah  is my fail.....   Language   client must be english ;)
