### ISSUE TITLE
Error at line 1

### ISSUE THREAD

**Issue by joris-s-k** [PoE-TradeMacro/POE-TradeMacro#498]
![error](https://user-images.githubusercontent.com/19972862/30100380-f8df624c-92e8-11e7-9e9e-801d2f8c6b12.PNG)

Error on starting Run_TradeMacro.ahk.

Happens with 2.5.4 and 2.5.3

**Comment by Eruyome** [comment]
First of I'm not sure it's a good idea to put ItemInfo/TradeMacro into the Path of Exile folder.
Secondly, why is your folder called ItemInfo when you're using TradeMacro? Did you install both projects and put them into the same folder? Unless you simply decided to use that existing and empty folder or just renamed it that way I wouldn't recommend it.

I suggest that you completely remove both projects (or the one that you have), including all contents of %USERPROFILE%\Documents\PoE-TradeMacro.

Duplicate function definition of that function means that the file CalcChecksum.ahk is being merged/included more than once, which simply doesn't happen normally.

**Comment by fuzzywolf** [comment]
For what it's worth, I'm getting the exact same error.  Downloaded the latest release (because the self updater failed).  Extracted to %user%\Documents\poeTM.  Failed with this type of error, except the path given in the error is %user%\lib\CalcChecksum.akh

**Comment by aRTy42** [comment]
When you manually downloaded the latest version, did you extract it into the existing folder? If so, please delete or rename the existing folder and extract the download into a fresh folder.

**Comment by fuzzywolf** [comment]
Deleted everything, restarted computer, re downloaded, extracted to fresh folder.  Error persists.

On windows 8.1, if that matters.

**Comment by fuzzywolf** [comment]
Started downloading and extracting old builds (I skipped a few in personal use).  2.4.0 works.  2.5.0 does not.

I know that was a big update, so the info may not be super helpful :(

**Comment by aRTy42** [comment]
Are you sure the error says "%user%\lib\CalcChecksum.akh"? Shouldn't there be a few more folders in between, something like "%user%\Documents\poeTM\lib\CalcChecksum.akh" from what you wrote ealier.

Also, just to be sure: What kind of autohotkey version are you using? If you are unsure: Launch the "Autohotkey.exe" itself, wherever you have installed that one and click on "Quick Reference" on the left side. It should tell you the version number in a huge font.

**Comment by fuzzywolf** [comment]
Yes, there *should* be a few more folders in there.  The path in the error message does not actually exist.    

I'm running 1.1.26.01, the latest version of AHK.

**Comment by aRTy42** [comment]
Ok, about that user/documents folder then: Is that "poeTM" a folder you created, or was that a shorthand type thing you used here for the "%user%\Documents\PoE-TradeMacro" folder? Because that folder is created by the script to save personalized things away from the regularly changing main folder. Could you try extracting the program to a place that is similar to your other programs (I'd guess something like C:\Program Files\POE-TradeMacro).

Please check that you didn't leave several old/other versions extracted somewhere that might interfere and please check that the user folder at "%user%\Documents\PoE-TradeMacro" isn't filled with odd stuff. There should be 4-5 .txt files and three subfolders (backup, CustomMacros, data) which also contain a few .txt files. When in doubt and you don't mind adjusting your settings again: Delete that folder to have a clean start.

**Comment by fuzzywolf** [comment]
Ah yes, poeTM was what I called the folder I extracted to.

Deleted everything again, extracted 2.5.5 to C\ProgramFiles\poeTM and  . . . it works.  Thank you for the help.

**Comment by aRTy42** [comment]
Great. One down.

joris-s-k, since we successfully hijacked your thread, could you also try to extract/install the script somewhere that is not a subfolder of some Steam/PathOfExile/User folder − such as C:\Program Files\POE-TradeMacro or whatever suits you.

**Comment by joris-s-k** [comment]
Moving it from a subfolder inside the PoE-Item Info folder to the PoE directory (Steam Folder) resolved the issue. 

Still no idea why it suddenly stopped working. I had it in the Item Info folder for ages without any issues.
