### ISSUE TITLE
Hotkey F5 go to Hide Out not work. when updated 2.6.0

### ISSUE THREAD

**Issue by kavana211087** [PoE-TradeMacro/POE-TradeMacro#564]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

hi team, 
i got to use update version 2.6.0 and hotkey go to hide out not work. 
another hotkey work good.

**Comment by dein0s** [comment]
1) Right-click on TradeMacro icon in tray, select `Show all assigned Hotkeys`, make a screenshot of the appeared window and attach it.
2) make a copy of `AdditionalMacros.ini` file from your `<WindowsUserFolder>\Documents\PoE-TradeMacro\` folder, rename it into `txt` and attach it (or just copy-paste its contents).

**Comment by kavana211087** [comment]
thank you.

**Comment by avuxyz** [comment]
![untitled](https://user-images.githubusercontent.com/32917782/31750427-3962ac7e-b4aa-11e7-9a3d-b327fd6f3c32.png)
[AdditionalMacros.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/1396845/AdditionalMacros.txt)
 My hotkey maybe cant use too

**Comment by Eruyome** [comment]
Was there any progress with this or do you guys still have issues?

**Comment by avuxyz** [comment]
Hi there, just download 2.6.0-beta2 and try but still have issues. i cant
use any hotkey.
so, i use 2.5.7 and its work

2017-10-23 23:08 GMT+07:00 Eruyome <notifications@github.com>:

**Comment by aRTy42** [comment]
There is a program called "AutoIt3 Window Spy" (AU3_Spy.exe) that comes with Autohotkey which tells you attributes of the current window. These attributes are what the TradeMacro uses to determine whether the PoE client is the active window and consequently whether the macros should work or not. I'd like to know what you guys have there.

If you got a search bar for programs on your PC you can probably just search for "Spy". Otherwise go to your Autohotkey (not TradeMacro!) installation folder and use the AU3_Spy.exe.
Open your game client, tab to the Window Spy and click into the game client again so that the client is the active window. The Window Spy should remain visible and tell you something like [this](https://puu.sh/y5SMT/63d404fa35.png).
Use Winkey+A to freeze the current information and copy the content of the first box, in my case:
```
Path of Exile
ahk_class POEWindowClass
ahk_exe PathOfExile_x64.exe
```
Post that information here.

**Comment by Eruyome** [comment]
1. Got to `%Userprofile%\Documents\PoE-TradeMacro` (you can paste this into the explorer to navigate there).
2. Make sure this folder is empty.
3. Make sure your TradeMacro folder is not on your desktop or somewhere in this mentioned directory (no subdirectory either).
4. Show us your "installation path".
5. Start the macro again via `Run_TradeMacro.ahk`.
6. Tell us if you're using a non-latin keyboard layout.
7. Report back.

**Comment by Eruyome** [comment]
I'm closing this until there are further reports.
