### ISSUE TITLE
Improve Ctrl+F Additional-macro: Highlight the Stash Search Box if Hovering Over Nothing

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#582]
Path of Exile, with no macros, has default Ctrl+F behavior coded. E.g., if you have the stash/atlas/passives open and Ctrl+F, the Search/Highlight box gets focus.

I recently discovered the Ctrl+F additional macro. It's great, but for one thing. **With stash open**, if i'm not hovering over an item, Ctrl+F should highlight the Search box.

AHK version: 1.1.26.01
Windows version: 10

**Comment by aRTy42** [comment]
Highlighting the search bar when there is no item is the current intended behaviour and is working for me. Can you double check that is does not work for you, please.

Are you using a non-latin keyboard layout, e.g. russian?

**Comment by dsnvwlmnt** [comment]
Normal keyboard. I have F assigned to a skill. Maybe that's affecting things somehow? When i click Ctrl+F with nothing under the cursor, the Events tab opens (why???) and my F skill triggers...

In the Atlas and Passive tree, the Events tab also opens when i Ctrl+F, but, at least the search box becomes highlighted.

With the macro's State=off, Ctrl+F works perfectly normally. Events tab does not open, F skill never triggers.

**Comment by aRTy42** [comment]
Which key is your events tab bound to? The skill on F shouldn't be an issue.

**Comment by dsnvwlmnt** [comment]
Events & PVP is bound to C. What is going on with the macro here? Hah.

**Comment by aRTy42** [comment]
The macro is using Ctrl+C to get the item data from the game. If your events tab opens it suggests that the key combination did not work as intended. I've seen two other active AHK scripts in the screenshot you posted in the issue about the settings menu, those might be in conflict with settings or actions from the TradeMacro. Please check whether the issue remains when only the TradeMacro is active. If it turns out to be a script conflict we can probably sort that out, but then we know what to look for.

**Comment by dsnvwlmnt** [comment]
Exact same issue continues to occur solely with TradeMacro open.

I have Events and PvP bound to C. Maybe TradeMacro doesn't handle that use case?

**Comment by aRTy42** [comment]
No, that alone isn't the issue, I've got something bound to C aswell. Also the script isn't supposed to send just C, it should send Ctrl+C, so the part about Ctrl getting lost is odd.

Please right click the systray icon, choose "Show all assigned Hotkeys" and post a screenshot of that window.

**Comment by dsnvwlmnt** [comment]
Note that in the screenshot i have ctrl+f disabled, but it was enabled for all the bug testing above.

![image](https://user-images.githubusercontent.com/14173022/32529354-f088038a-c3ec-11e7-9195-b74144e0ba72.png)

**Comment by aRTy42** [comment]
I currently have no idea what to check next, I'll need to spend a while with the relevant code section. I don't have that much time today though, so I'll probably get back to this tomorrow.

**Comment by aRTy42** [comment]
I still can't grasp how your exact issue might happen. There are some things in the code where I can imagine a malfunction, but it wouldn't just fail on not-item-hovering.

Could you activate the highlight function in the AdditionalMacros again please and use a different keybind (instead of Ctrl+F), something like F6 or any other F-key, in particular no combination with Ctrl.
Please test that new binding without any other macros running. Report any odd behaviour like opening game windows, activating skills or alike.

**Comment by dsnvwlmnt** [comment]
Identical behavior whether assigned to Ctrl+F, or F6.

With stash open, when i click F6 with nothing under the cursor, the Events tab opens and my F skill triggers.

**Comment by Eruyome** [comment]
Could you make any progress with this? I still have no idea why the script could behave in that way for you.

**Comment by dsnvwlmnt** [comment]
Tested using your new hotkey UI. No change, whether using Ctrl+F or e.g. F2. Both HighlightItems and HighlightItemsAlt have the same effect described previously.

**Comment by dsnvwlmnt** [comment]
Well, oddly enough on another computer i have exactly the same issue. Clearly the commonality here is my PoE settings. Could try testing using my production_config.ini. Maybe just use my [ACTION_KEYS] to start and see if that replicates the issue.

https://pastebin.com/zCNiXi09

**Comment by zynaxsoft** [comment]
I also have some weird behavior. When my cursor is on the ground not pointing at any item, it toggles the inventory.

I have the inventory hotkey bind to "c". Binding it to "i" or other keys seems to fix the issue.

**Comment by Eruyome** [comment]
If this is still an issue please open this again/reply.
