### ISSUE TITLE
Do Not Wipe the Clipboard on Launch

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#583]
I've noticed this macro wipes the clipboard on launch. Please don't do this if at all possible. A program shouldn't wipe the Windows clipboard without asking.

AHK version: 1.1.26.01
Windows version: 10

**Comment by aRTy42** [comment]
Most functions of the script involve taking the item data from the clipboard, so having a clipboard change is a common thing when using this script. What do you have in the clipboard that is so crucial?

**Comment by dsnvwlmnt** [comment]
I use lots of TradeMacro features and i've never noticed any clipboard interference other than on launch. It doesn't really matter what i have on the clipboard, but i'll tell you anyway, it's poetrade pastes that i copy while the game launches.

But let me turn that around and ask: why are you clearing the clipboard on launch? A less intrusive method would be to initialize the clipboard before the first time you actually put something in it or make use of it.

**Comment by aRTy42** [comment]
Every function that involves an item uses the clipboard and I think Ctrl+F is the only one that specifically restores it. So most functions do delete or overwrite the clipboard.

Concerning the launch: The relevant TradeMacro part is not from me, but I found this in the initializer:
```
; empty clipboard on start to fix first search searching random stuff
Clipboard := ""
```
so the empty clipboard is not an accidental byproduct of starting things, it is intended. Eruyome would be the one to ask why this is necessary, but the more important part for this issue is that I doubt it will be changed.

**Comment by Eruyome** [comment]
; empty clipboard on start to fix first search searching random stuff
Clipboard := ""

That's from the TradeMacro code. So there is a reason for this, but there should be a better solution.

**Comment by Eruyome** [comment]
Fixed.
