### ISSUE TITLE
poeprices.info

### ISSUE THREAD

**Issue by CaptainMyCapt** [PoE-TradeMacro/POE-TradeMacro#616]
Using the new price search doesn't seem to actually take into account the mod range % modifier seemingly defaulting to 30% which is not terribly useful on a large number of mods.

An option to return both predicted and recommended prices would be nice.

Likewise a way to cancel the pricing attempt or at least set a less obnoxiously long timeout for when the site isn't responding would be good.

**Comment by Precursorx** [comment]
Currently waiting for a response from poeprices also seems to disable all other shortcuts making scrolling though your stash while waiting for the result frustrating when you are used to ctrl-scolling

**Comment by jaaqov** [comment]
You can tick a box to get back into the default search via the options - buy I agree, the pricing via the new tool is lagging behind and most of the time can't find any results and just dies why it is searching.. should be disabled by default till it is working as intended!

**Comment by Eruyome** [comment]
Sorry for the late answer, took a week off. Anyway, the tiemout isn't that high, or at least not anymore, the search seems to work far better now also. I believe there's no need to make it not the default since you get a clear notice that you can easily deactivate it.
@Precursorx  AHK doesn't really have asynchronous code execution, so I can't do much about that.
@CaptainMyCapt I'll think about it, not a big fan of making multiple request to different sites, for example because of the mentioned async issues.
