### ISSUE TITLE
Will you add abyss jewel tier list + shaper elder roll support

### ISSUE THREAD

**Issue by marat569** [PoE-TradeMacro/POE-TradeMacro#629]
Basically the title.

Will you add support for the tiers of abyss jewels and their affixs?

Shaper/Elder rolls aren't really required, but was just adding this in the post to ask what your plans are with them.

Thanks for the amazing app!

**Comment by aRTy42** [comment]
The new t1 mods and the abyss jewels are already done and released for ItemInfo, Eruyome just didn't do another TradeMacro release since then. If you want to wait for a regular release, you can technically download the update branch that is pending to be included.
If you do so, unzip it to a different folder than your regular TradeMacro install please, don't mix the two. You'll also see a bunch of extra files that get removed for regular releases, just ignore those and use the "Run_TradeMacro" as usual.

The branch can be found [here](https://github.com/PoE-TradeMacro/POE-TradeMacro./tree/UpdatesFromItemInfo).

**Comment by Eruyome** [comment]
Updated soon.
