### ISSUE TITLE
Update-check failed, Exception thrown!

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#644]
Why do i get this every frickin update? And then i always have to manually click Check for Updates. Can this thing automatically update please, thanks. :P

![image](https://user-images.githubusercontent.com/14173022/34634048-4759bd0e-f235-11e7-9b91-c2a6ed3d149a.png)

**Comment by aRTy42** [comment]
Probably because the whole "My Documents" folder has restricted permissions and blocks script execution or file writing.
Put your whole "PoE-TradeMacro" main script folder somewhere else, for example in the "Program Files" folder.
**Do not** move the user files folder though, which is probably at "My Documents\PoE-TradeMacro" for you and contains a few .ini files.

**Comment by dsnvwlmnt** [comment]
Then why does the macro create files and work just fine, and Check for Updates updates everything correctly? I guess i don't know the inner workings...

**Comment by Eruyome** [comment]
What TM version are you using?

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

This should work for you, but it's only a hotfix, preventing the script to fail when the WinSet command causes an error. You can edit `<TM folder>\resources\Version_Trade.txt` and lower the version number, then start the script to simulate an update.

**Comment by dsnvwlmnt** [comment]
It happens pretty much every version lately, maybe ever since i turned off the splash screen option. In this case i had version 2.7.4.

AHK 1.1.26.01

**Comment by Eruyome** [comment]
But, does it work now with my fix? I'm expecting it but confirmation is always nice.

**Comment by dsnvwlmnt** [comment]
Yep it works. Simulating pops up the update screen instead of the error.
