### ISSUE TITLE
F1 hotkey

### ISSUE THREAD

**Issue by ARBZM** [PoE-TradeMacro/POE-TradeMacro#645]
Hi, every time i pressed F1 (my own custom macros) i got message about item stats/price check.
Tried to find at files any word about "F1" as hotkey and remove it, but i cant. can someone pls get advice where i should check "F1" as hotkey(which file) to change it? thanks.

AHK version:  1.1
Windows version: 7 he

**Comment by aRTy42** [comment]
Does your own F1 macro use Ctrl+C to get the item clipboard data from the game?

**Comment by ARBZM** [comment]
nop. used for flasks only (2,3,4,)

**Comment by aRTy42** [comment]
Did you put that into the Custom-Macros folder or are you trying to run another .ahk file in addition to the TradeMacro?

**Comment by ARBZM** [comment]
im not a dumb)) sure i used it from custom macros. but if i used ctrl+c/ctrl+d on item for check stats/price and after it i press f1 there is a message about price/stats again.

**Comment by Eruyome** [comment]
While I'm not sure what your issue is I have to note that your flask macro is against GGGs Terms of Service since it causes multiple server side actions with one button press.

**Comment by ARBZM** [comment]
i know, ty

**Comment by aRTy42** [comment]
There are multiple errors in your code. Key definitions require two colons, not one, and since your input is multi-line you'll need a "return" at the end.
That being said I won't provide further support for this issue. Please be very clear that I don't approve breaking the TOS and strongly recommend that you look for alternatives, such as using three keybinds that are comfortable for you to press in a group.

**Comment by ARBZM** [comment]
thanks, lol, rly missed return at the end.
