### ISSUE TITLE
"Put tooltip results on clipboard" conflicts

### ISSUE THREAD

**Issue by lemasato** [PoE-TradeMacro/POE-TradeMacro#663]
Hi there,  
This setting seems to be messing with the clipboard in cases it shouldn't [(See here)](https://github.com/lemasato/POE-Trades-Companion/issues/95#issuecomment-358387264)

### Reproducing the issue:
1. Have TradeMacro running.
1. Have "Put tooltip results on clipboard" from the ItemInfo tab enabled.
1. Run this sample script and press Numpad1 on PoE while chat is open:
```
#SingleInstance Force

Numpad1::
Clipboard := "Sample Text"
ClipWait, 10
SendInput, ^{sc02F}
Return
```
Sometimes, no text will be sent at all.

### Potential fix:
Only replace the clipboard content when the data match those of an item:

POE-ItemInfo.ahk, line 6892
Replace `If (Opts.PutResultsOnClipboard > 0)`
With `If (Opts.PutResultsOnClipboard > 0 && ParsedData)`

**Comment by aRTy42** [comment]
Included in the PR to the TradeMacro that I did for ItemInfo updates. It's not in the 3.1.01 ItemInfo release itself because I did not have this issue on my radar at the time. The same fix should go into the standalone ItemInfo with its next release, but most people use the TradeMacro anyway. Just so you know, in case any Trades-Companion user has the same issue with just ItemInfo in the meantime.
