### ISSUE TITLE
[Feature] Validate items mods to decide if item is "good" or "bad"

### ISSUE THREAD

**Issue by mindyk** [PoE-TradeMacro/POE-TradeMacro#67]
!! New Issue for this: https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/83 !!

either the results are empty , or i get this message. Why are rolls being ignored? Did i miss any setting ?

**Comment by Eruyome** [comment]
Either you didn't read the tool description/faq or there's something wrong. Mods are always being ignored unless you use the advanced search for uniques and select mods. And I need more information about the items you're checking to say something about the empty results. Try ctrl+q to open the search on poe.trade and see what was actually used in the search (filled form).

**Comment by mindyk** [comment]
ah , i see! My bad, i was not aware about the "rares do not work yet" thing.  How about implementing this guide as first step?
https://www.reddit.com/r/pathofexile/comments/56rtmk/the_is_this_item_worth_something_guide/

should be easier then the "real" thing. And people would get a thumbs up or down. And in case of thumbs up they could invest the time on poe.trade and thumbs down would save them the time

**Comment by Eruyome** [comment]
I'm not sure I understand what exactly you mean when you're talking about implementing the guide and poeple getting thumbs up/down. Could you elaborate on that a bit more?

Do you mean checking the item against these criterias and displaying a symbol to indicate it's a good/bad item?

**Comment by mindyk** [comment]
> Do you mean checking the item against these criterias and displaying a symbol to indicate it's a good/bad item?

that is exactly what i mean. Something like "you should check out poe.trade, this item could be worth something" and "dont bother looking this up"

**Comment by Eruyome** [comment]
Well, that's a nice idea but probably very challenging.

First of, it can be very hard to decide what's important about a normal/magic/rare item. We have 5l/6l, good crafting bases (iLvl dependend), corrupted implicits, enchantments (some totally worthless, some more valuable than almost any helmet you could buy because of its mods). Some times the mods on the item can be irrelevant to get a good idea of its value. And btw, I don't think it's feasible to make and maintain a list of good and bad enchantments.

Then we need a similiar list (like from the guide) for every item type, frequently maintained by knowledgeable people to be accurate. Then we need some logic behind it to decide how many of those mods are necessary on the item to be considered valuable, maybe even weighting every mod.

I believe that's something that will only happen with community effort, not as long as I continue to work alone on this project as I currently do.

**Comment by Eruyome** [comment]
To be precise, this list should be maintainable by non-programmers but include all the information to parse the items mods and get a thumbs up/down. Could be hosted anywhere, googlesheet, dropbox text/json file etc..

**Comment by mindyk** [comment]
it does not have to be perfect from the start. Everything is better than nothing. You could ignore enchantments (like u ignore rolls right now?) (- :

i have some programming background. Maybe i could hack a prototype or something. Would you be available for questions to kickstart my AHscript knowledge?

**Comment by Eruyome** [comment]
Sure, you can always ask, discord and gitter are good, gitter is probably better. I believe for now it would be important though to get an idea on how this information could be provided, how such a list has to look like. I think it's better to not have such a feature at all than having it poorly implemented. That doesn't mean the list has to be complete and include all important mods, it could be only life + resists for the start. But we will have to know what mods are important, what mods have to present on the item in combination, how high their values have to be and maybe even a weighting. With a good system it could be easy to read and process this information, without writing too complex logic.

Maybe actually a googlesheet (can be downloaded on script-start as json for example)

**Comment by Eruyome** [comment]
moved to new issue https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/83
