### ISSUE TITLE
Running macro change keyboard layout (azerty to qwerty)

### ISSUE THREAD

**Issue by Mwoua** [PoE-TradeMacro/POE-TradeMacro#688]
When the ahk script is running, any software launched on the computer are started with qwerty layout

When stopping the script, everything back to normal.

If a software is launched before the script, it will keep its layout. Only software launched after the script will have the qwerty layout

AHK version:
1.1.27.07 64 bits
Windows version:
windows 7 64 bits

**Comment by D0ntCallItSchnitzel** [comment]
Can confirm.
I came back to PoE after Harbinger league and (re-)downloaded the newest version of PoE trade macro (+ AHK 32 bit) a few days ago.
Kinda freaked out when it suddenly changed the default layout of german (qwertz) to us-english (qwerty) ingame and some of the other running programs/softwares.
Since I didn't/don't have the keyboard language/layout selection activated on the Windows 7 toolbar, I thought that I accidentally messed up everything with keyboard shortcuts at first, so I just performed a system recovery to avoid the whole hassle.
When it happened again I looked further into it and realised that the 'PoE (Trade) Item Info Settings' window itself is always set to us-english (or qwerty) regardless of the default language/layout settings you have and kinda "infects" the running programs/softwares with its own layout.

My temporary solution for non-qwerty users would be to delete the layout (and maybe some others) from your Windows keyboard layout settings so that you mainly use your prefered language/layout and the macro has no others to change to.

AutoHotkey version:
1.1.28.00 32 bit
Windows version:
Windows 7 Professional 64 bit

**Comment by aRTy42** [comment]
For me within the settings menu the keyboard layout becomes EN, but otherwise nothing is changed or affected.

Are you pressing Alt+Shift for some reason? Could you also check if that's the hotkey for the windows keyboard layout change for you − it might be set to a different key combination that might explain the issue.

**Comment by Mwoua** [comment]
In the last few days, I didnt have the issue anymore (didnt update anything) so maybe, launching the script and poe in a specific order can change something.
I'll try to run more test tonight.

About alt+shift, when I had the issue, I could alt+shift inside an application, and it would return to my keyboard layout, but using alt+shift on windows desktop had no effect

**Comment by D0ntCallItSchnitzel** [comment]
In my case, the first time it happened (yesterday) I also thought that I messed something up with Alt+Shift and performed a system recovery as I mentioned before.
Today it happened again and I could confirm that it wasn't on me, because I kinda would remember pressing it a second time due to the quite unusual finger pose it takes for me to do it in the first place (I believe I never even used the shortcut to change the language/layout before).
I don't know how the the problem exactly appears (but as Mwuoa said, it probably has something to the with the order of starting PoE and the macro), but I was even able to recreate it a few times after some testing, resulting in it changing the layout at first ingame, then for things like Firefox and some other Windows applictations.

**Comment by aRTy42** [comment]
There is something in the script that changes the layout to english within the settings menu, but Eruyome and I don't see why that would overwrite anything outside of that window, let alone the whole application.

Could you check the priority ordering of your keyboard layouts please. The window should look like [this](https://i.stack.imgur.com/FZLFQ.jpg) and your prefered input should be selected in the drop down list at the top.

**Comment by D0ntCallItSchnitzel** [comment]
Right now I have only my prefered layout (german - qwertz) in there as part of 'temporary solution' I discribed in my first post to avoid the hassle of it eventually affecting my running applications again.
Before that it was first/above german then us-english with the 'default input language' also set to german (so basically the factory settings with german as your language).
I'm pretty sure it didn't affect the these settings, only individual applications and (in my case) saved/set their prefered languages/layouts, which remained even after I shut down the macro.
To revert it after some testing I had to delete us-english from the settings you asked for so it set every individual preference back to german as the only option available and add us-english back to the list.

Don't know what else I could tell you other than pretty much confirming that it indeed changes the layout to qwerty on its own under the right circumstances (maybe Windows 7 or AHK itself plays a big part in that).

**Comment by Mwoua** [comment]
Its definitly linked to the settings menu. I started the script, everything was fine, I opened the menu, boum qwerty on all my applications.
Closing the menu didnt change anything, and at the moment, im stuck in qwerty with the script closed

**Comment by Mwoua** [comment]
Didnt change anything, and again, the macro switch my keyboard layout on startup

**Comment by Eruyome** [comment]
Still got problems with this? Found any permanent solution?

**Comment by Mwoua** [comment]
I updated to windows 10 and dont have the problem anymore.

**Comment by Eruyome** [comment]
Ok, I guess I'll close the issue for now.
