### ISSUE TITLE
Error at line 1

### ISSUE THREAD

**Issue by Blackscroll** [PoE-TradeMacro/POE-TradeMacro#695]
* AHK v1.1.28.00
* Windows 10

been using 2.8.0 for last week no issues. Started macro today and got attached error. Macro install path is this: F:\POE-TradeMacro-2.8.0

made sure AHK is up to date, uninstalled both ahk and macro made sure there was no other data lying around for either. re-installed and still getting same error.

any ideas?

![capture](https://user-images.githubusercontent.com/37668362/37785400-f598ec58-2df1-11e8-8670-d4de4aa7f6bf.JPG)

**Comment by Blackscroll** [comment]
Fixed this my self, tested on two machines but it seems the macro will not run in AHK is installed on another drive, don't know why this has now changed as previously I always had AHK on C: and macro on F: but moving macro over to C: as well has fixed the issue.

**Comment by Eruyome** [comment]
The other drive shouldn't be the issue, that works for me and others. The error message mentions a duplicate function definition, normally that means there are some remnants of other TradeMacro installations/versions somewhere. Of course this seems a bit weird since you said you removed everything. Even weirder is that the path mentioned in th message is a `lib` folder on your drive root, not the one in the TradeMacro folder.
