### ISSUE TITLE
Improving the PoePrices dialogue

### ISSUE THREAD

**Issue by nijikokun** [PoE-TradeMacro/POE-TradeMacro#696]
I changed the dialogue for the PoePrices, It's a little rough but it adds what I wanted which is the "Recommended" price by parsing the HTML:

![pathofexile_x64_2018-03-25_17-13-23](https://user-images.githubusercontent.com/198276/37881664-5323ea66-3050-11e8-9d19-d282d96b3be6.png)

I also removed the feedback ui because i never use it. would be cool to have a setting.

Here is the code changes:

https://gist.github.com/nijikokun/59e714dac3fccc0e691ecff18eb75b9f

If you use it or find inspiration that's cool, I was thinking about making a PR but I can probably just copy paste these on update so I'm not sure I will.

**Comment by Eruyome** [comment]
I've talked with the peoprices devs, well one of them, about the recommended price before. It's something that may not be there to stay. It also needs a different/second server request to get this price, therefore we decided that I shouldn't include it.

About the feedback UI, it would be a bit unfair to remove it or add an option for that. They need support to keep their serves going and they need feedback to improve their predictions. I believe both UI parts are seperated clear enough so that the feedback part can be easily ignored.

I'm not saying we can't talk about including more information but I don't want to simply scrape their html instead of finding a solution together with them.

**Comment by nijikokun** [comment]
Fair points, JSON object didn't have recommended so scraping the HTML was the only way. I'll be using this until it goes away, and when it goes away then I'll probably end up using poe.trade since the range isn't useful at all.

Not sure I agree that the "feedback ui" is required for support, could just be a link to go to the site and leave feedback there, they have a decent ui for it.

**Comment by nijikokun** [comment]
I don't care enough, about this, to argue or debate about whether they need support, whether the feedback UI gives them that _support_, or whether scraping is a sub-optimal solution considering the tool does it in other locations.

If someone wants to do this, the above is there, that's how it's done.

**Comment by Eruyome** [comment]
TradeMacro only scrapes services that can handle it though, the poeprices servers "died" a few times in the past already and were offline for a few hours because they couldn't handle the requests, most of them coming from TradeMacro, so I tend to be careful about that.
