### ISSUE TITLE
The cookie value "cf_clearance" isn't support by poe.trade anymore

### ISSUE THREAD

**Issue by Supportic** [PoE-TradeMacro/POE-TradeMacro#697]
Trying to fill out the manual cookie selection and everything is sending but "cf_clearance".
Tried it in Chrome and Firefox.
Therefore it doesn't take all attributes of my item to fill in the gaps in poe.trade.
It's working with poeapp.com tho.

AHK version: 2.8.0
Windows version: Win 10 (x64)

**Comment by Eruyome** [comment]
This issue is a bit tricky since the response that you need cookies may be false. Basically it only shows that the connection fails, which may be related to cookies in some cases but could have other reasons.

So please make sure whether you need cookies to access poe.trade in your browser (delete all cookies first). If there's no cloudflare redirect page you're good.

Secondly upload/post `<TM Folder>\temp\StartUpLog.txt` here.

**Comment by kjy112** [comment]
"cf_clearance" cookie is not present when looking for poe.trade cookie. This is causing the PoE-TradeMacro to hang during cookie retrival. I used to launch it several times to get IE cookie retrival window to pop-up but now it doesn't seem to even allow that. So, I can't click "continue" to use the rest of the POE tradeMacro functionalities.

![untitled-2](https://user-images.githubusercontent.com/339956/38202639-6b1b3f78-366a-11e8-9aa0-6639e689487e.jpg)


Is there a way we can by pass this warning pop-up?

**Comment by Eruyome** [comment]
It's not unusual for the cookie not to be present but I'm not aware of the issue of the script completely being stuck because of it.
