### ISSUE TITLE
Help change basic hotkeys

### ISSUE THREAD

**Issue by devellaro** [PoE-TradeMacro/POE-TradeMacro#704]
I recently installed this, and it all seems to work fine so far. Kudos to the creator!

I would however, like to be able to swap the hotkeys that are normally ctrl + c(item info), and ctrl + d(price check)

Optimally I would prefer my mouse scroll wheel to operate ctrl C on the up movement, and ctrl D on the down movement. Possibly Alt + Scrolldown, for the Advanced price check. Alternatively I could use simle F keys without modifiers. But am unable to change ctrl C still, even if that is my only option rather than mouse wheels.

I found an option list (PoE (Trade) Item Info Settings) to change pretty much any other hotkey, except for ctrl C. The control d is listed on the first page, but I cannot figure out how to set my mouse wheel to replace ctrl d. :(

The link right underneath tells something about coding the wheel to a hotkey, but nothing in this interface has allowed me to do something of the sort.

I need to change the base script I assume, but I don't want to totally screw something up.

So if any kind individual would tell me which file to modify, and how... I would appreciate the help.

PS I was able to change the ctrl D, to use the F1 key instead, but it is not my fav option. I tried editing the config.ini for the ctrl C, but it did not work.

AHK version: v2.8.0 for poe 3.2
Windows version: win10 x64

**Comment by aRTy42** [comment]
Using just scroll could cause odd surprises, but it's up to you if you want to try them. I've tested it and it is possible, but I didn't test long regarding potential bugs. If you want to be safer, use the Alt+Scroll variants.

For Pricecheck:
The regular options window does not support the mousewheel, but you can edit the config file. Right click the TradeMacro icon and choose "Open User Folder". Open the "config_trade.ini" and make a change in this section:
```
[Hotkeys]
; see http://www.autohotkey.com/docs/Hotkeys.htm for hotkey options
PriceCheck=VK9E
```
The code "VK9E" is equivalent to "WheelDown". Note that the options window will show an empty field if you use this one, but from what I've tried it should keep this entry (and not overwrite/clear it) if you don't touch this specific options field afterwards, meaning the options window should be safe to use for other changes.

For Ctrl+C:
Currently you can't overwrite the hotkey itself, because it is tied to the native ctrl+c game client function. You can however define an additional hotkey that sends the ctrl+c command to the game, so you can use WheelUp as an alternative.
Open the settings menu, go to the "AdditionalMacros" tab, put a tick at "SendCtrlC" to enable the function and use the edit button to change it to the mousewheel. In this case the wheel should be correctly detected when used.

Restart the script to have the hotkey changes take effect.

If you decide to use the Alt+Scroll variant, put an "!" before the key code, so "PriceCheck=!VK9E". The AdditionalMacro menu should detect Alt+WheelUp just fine again.

**Comment by devellaro** [comment]
Thank you very much, everything worked.
