### ISSUE TITLE
Copy doesn't work in Dvorak keyboard layout

### ISSUE THREAD

**Issue by melbaa** [PoE-TradeMacro/POE-TradeMacro#708]
Scan code `sc02E` is `j` in the Dvorak keyboard layout, so the copy function doesn't work. This is the opposite of https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/126, because `^{c}` fixes it. 

The scan code for `c` is `sc017` in the Dvorak layout.

Currently trademacro sends `j` to the game, which triggers other ingame hotkeys.

**Comment by Eruyome** [comment]
I believe the only way to fix this is by detectin a dvorak layout, which may be possible. The script already detects layouts and temporarily switches them at startup.

When switching to Layout "English (Dvorak)" the script returns the code `0xF0020809` . Normally you can get the layout from this by comparing the codes with this list https://msdn.microsoft.com/en-us/library/cc233982.aspx, but I have no idea how to know for sure if the layout is Dvorak or not, using my example code. Maybe I'm bad at researching this but I can't find the neccessary information.

I can try to get it by testing (0xF0020809/0xF01B0809/0xF01A0809):
- 0809 is for "English United Kingdom"
- 0xF002 seems to be for "Dvorak"
- 0xF01B seems to be for "Dvorak right handed"
- 0xF01A seems to be for "Dvorak left handed"

Now, I guess I can be quite sure of this being true and accurate but I'm not entirely sure that I can't mess anything up by using a different scan code if these sub strings are found in the language ID.

Also, considering that you're the first person since the macro exists to complain about Dvorak support, I'm not willing to thoroughly test the entire macro for adding Dvorak support. If you can tell me that everything else works flawlessly using Dvorak, including setting your own hotkeys in the settings menu for TradeMacro and AdditionalMacros and only the `c` scancode is an issue, then I can make a test version with a scancode switch in the near future. I'm hesitant to add support for something that may introduce a bunch of other issues, especially if practically nobody uses it anyway.

Here's the AHK code btw:
```
#SingleInstance force
SetFormat, Integer, H
WinGet, WinID,, A
ThreadID:=DllCall("GetWindowThreadProcessId", "UInt", WinID, "UInt", 0)
InputLocaleID:=DllCall("GetKeyboardLayout", "UInt", ThreadID, "UInt")
MsgBox, %InputLocaleID%
```

**Comment by melbaa** [comment]
> Also, considering that you're the first person since the macro exists to complain about Dvorak support, I'm not willing to thoroughly test the entire macro for adding Dvorak support.

That's fair, I'm sure there's plenty of better gameplay related things to do. I think there's still value in the discussion and we might come closer to a solution.

> If you can tell me that everything else works flawlessly using Dvorak

Everywhere scancodes are used, we are in trouble (as you probably know, scancodes bind more to the physical location on the keyboard than the meaning of the key pressed), luckily there seems to be few such places. The only other major issue is CTRL+F doesn't work for me, because by default the HighlightItems functionality takes it over and sends the incorrect scancodes.

I don't think you need scancodes at all to support Dvorak, it's just an English keyboard layout after all. The scancode support is for layouts, English or not, that have cut-copy-paste under the X C V keys. I realize using scancodes, while not perfect, is contributed by people because it works for them, they are the majority and it's better to have something working than nothing at all.

> setting your own hotkeys in the settings menu for TradeMacro and AdditionalMacros

Yes I can change the hotkeys fine in both tabs, I have changed most of the hotkeys there .

**Comment by Eruyome** [comment]
In the end using scancodes is the best solution, otherwise I have to make a list of layouts that need the scancodes (by comparing the language IDs that I mentioned) and switch to using scancodes conditionally. As we can see scancodes are a good solution for everyone, besides egde cases like Dvorak.

I can try implementing what I showed already, reading the language ID, looking for `0xF002` etc and switching to different scancodes or to pressing keys (^c). If I show a popup at script start that shows the user that Dvorak support was enabled it should be pretty easy to identify any issues with it. Otherwise it would be hidden quite deeply that there may be an issue with the keyboard layout.

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/archive/devEru.zip

I have added dvorak support in this dev version. If a dvorak layout is detected the script shows a msgbox (has a timeout) to inform the user.

Here are the scancodes that I used, most of the are for the stash search highlight function.

```
sc := {"c" : "sc017", "v" : "sc034", "f" : "sc015", "a" : "sc01E", "enter" : "sc01C"}
```

**Comment by Kaeteker** [comment]
I use Dvorak too, and that dev build fixed the problems I was having. Thank you!

**Comment by Eruyome** [comment]
Nice, I'll close this for now, if any issues arise just open it again or message here.
