### ISSUE TITLE
^c currency worth lookup doesn't show for flashback league

### ISSUE THREAD

**Issue by f0lie** [PoE-TradeMacro/POE-TradeMacro#719]
This isn't a big problem since flashback is ending in a few days but it's worth pointing out. ^c gets its rates only for the current Challenge and Standard League since it's hardcoded for those two. It doesn't show the rate for the flashback league.

I figure this out noticed that Annulment and Ancient Orbs were much more expensive than what poe.ninja said. It turns out I was just looking at the rates for Bestiary and not flashback which made a lot of sense to me. ^d works just fine with flashback league though.

**Comment by Eruyome** [comment]
Thanks for reporting that, I found some issues with how TradeMacro handles these events because of it (writing them to ini and having invalid values when they are not available anymore without automatically writing correct values to the config).

Anyway, ItemInfo can still function as a standalone script and doesn't have TradeMacros league parsing. We prefer not to implement it, for now I have asked the poe.ninja dev to also make his API calls for event leagues available via alias, like it's already the case for challenge leagues.

**Comment by Eruyome** [comment]
Fixed for this and future event leagues.
