### ISSUE TITLE
[New Feature Implementation] Translate option

### ISSUE THREAD

**Issue by gvieiraaa** [PoE-TradeMacro/POE-TradeMacro#734]
I was going to contact via forum but I think here is more straightforward.

Some years ago I made an ahk script to help people translate item names from portuguese to english and vice versa.

It helped people getting item names to search on poe.trade, wiki or google, or even to help people that asks on global chats "how is this item name in enlish?" without the need to change the game language.

Since my last update the game has now several other languages. I think it could help other people and I will update and continue the project for all the languages in the next days, and I just thought that it could maybe be a good feature AdditionalMacros.

It can translate every item that is not a magic or rare item (because of the different syntax), including mtx, white bases, currencies, uniques, fragments etc.

Let me know what you guys think about it. If it's acceptable I'll fork, implement and test it myself before sending for someone to implement it.

The outdated project git: github.com/gvieiraaa/PoETranslator

**Comment by Eruyome** [comment]
I already tried implementing it, I haven't looked at your project but reliably translating the complete item is quite complicated. I more or less did it but the data for it wasn't complete/good enough. I took some files from GGGs trade site which have a lot of data but not exactly what I need. 

Here is some of that code:

https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/lib/PoEScripts_DownloadLanguageFiles.ahk

https://github.com/PoE-TradeMacro/POE-TradeMacro/blob/master/lib/PoEScripts_TranslateItemData.ahk

Anyway, I ran into issues that could only really be solved by correctly extracting all neccessary data from the .ggpk file or getting it from GGG. So I talked to Chris WIlson about it at length and he told me it's just not possible to create these files. I'm not completely convinced but he brought a few arguments that seemed somewhat convincing without knowing their backend. I tried pushing that the translated data will be added to the ingame item data, he also liked the idea to improve this. But I guess nothing happened so far and I'll probably annoy him soon again.

The thing is, TradeMacro is "too good", has "too high standards". I won't implement some partly working tool/bad solution that sometimes works. Maybe It's ok to add something that only translates item names but I really want to translate the entire item so that it can be parsed completely, used in PoB etc.

**Comment by Eruyome** [comment]
Btw, the item data improvements I was talking about with Chris would optimally look like this:
- Return everything as JSON
- Add translated strings for everything.

This would easily solve all problems, so I'd rather try pushing for that for now instead of implementing some complicated scripts.

**Comment by gvieiraaa** [comment]
I get all the item names from the ggpk using pypoe.

It's a different thing, but I'll take a look in the item data translation to see if I can help with that, it would indeed be a lot more usefull.

**Comment by Eruyome** [comment]
In case you want to test what I made so far, you can enable that stuff in any current TradeMacro version.

`\resources\ahk\PoE-ItemInfo.ahk` (remove comments): 
```
	/*
		;Item Data Translation, won't be used for now.
		CBContents := PoEScripts_TranslateItemData(CBContents, translationData, currentLocale, retObj, retCode)
	*/
```
and
```
/*
	;Item data Translation, won't be used for now.
	Menu, Tray, Add, Translate Item, ShowTranslationUI
*/
```

______________________________

`\resources\ahk\Merge_TradeMacro.ahk` (remove this): 
```
If (not PoEScripts_CheckCorrectClientLanguage()) {
	ExitApp
}
```

It should work then. It will mostly work with the german client though since I had to hardcode some stuff and didn't bother to to do all that work for all languages so far.

___________________________________

You can see all the files I'm using in the code but in case you don't know them, they exist for every language:

https://www.pathofexile.com/api/trade/data/stats
https://www.pathofexile.com/api/trade/data/static
https://www.pathofexile.com/api/trade/data/items
https://web.poecdn.com/js/translate.de_DE.js?v=b193b78dcea91321a37e6c483e5eb7b7

Here are some screenshots of my work https://imgur.com/a/TJjep

And here an example of the issues with said files:

> The biggest issue using your trade sites language files is translating the item affixes. This file https://www.pathofexile.com/api/trade/data/stats seems to contain every single existing suffix (internal id, text and type). Unfortunately the text is not the string that we can see on the actual item but the representation of it that is being used in the trade site UI. In some cases it's the same, in others not.
> 
> Example from the Wildfire Jewel:
> 
>     Language file: "With at least 40 Strength in Radius, Molten Strike fires an additional Projectile"
>     Actual text: "With at least 40 Strength in Radius, Molten Strike fires 2 additional Projectiles"

> This makes sense in the trade site UI, because it's a webform where you can enter a range instead of searching for "2 additional Projectiles".


> The item data has some strings that are nowhere to be found in all of the language files used by the website since they are not directly displayed/used on the search UI.
> Here's some JSON, some arrays of strings that I had to hardcode while testing my translation tool. For simplicities sake it's just english and german. Basically a lot of strings from the item data that come before the item suffixes have no translation. 

___________________________________

Btw a quote from Chris

> We have an internal representation of an item that is language agnostic. A set of stat IDs and values. We turn this into an English (or other language representation). This is essentially a one-way process, because we are not willing to publish our internal details of the way we store items. Attempts to translate from one language to another *correctly* will run into problems due to this lack of data.
> 
> As far as I can see, the only way that we can solve this is by adding tech so that you can get English ctrl+c info from foreign clients.

**Comment by j0hnnycode** [comment]
Any news on this, I hope we will get this done for 4.0? Poetrade is the only reason why I keep playing the game in a foreign language. Thanks for answering :-)
