### ISSUE TITLE
Call to nonexistent function. Specifically: TradeFunc_DoCurrencyRequest

### ISSUE THREAD

**Issue by Tatherwood** [PoE-TradeMacro/POE-TradeMacro#740]
So... My macro was running fine just yesterday. However, when I tried launching today, I encountered the error "Call to nonexistent function. Specifically: TradeFunc_DoCurrencyRequest", which informed me that the program will exit.

Now, I WAS running the macro from Desktop, despite the warning (simply because it's faster). So, I got rid of the macro and all its folders, downloaded again, and this time unziped in Documents (rather than desktop).
I created a Direct Access to Desktop, launched, and worked okay... except, on the bottom right (the trail thing?), the AHK was now on, but the actual TradeMacro one wasn't (you know, the one that lets us change the options, and switch what league we're searching for, and stuff). So I terminated the macro, launched again... and again got the error: Call to nonexistent function, specifically: TradeFunc_DoCurrencyRequest.

I know the general nonexistent function was the same both times, but I honestly don't know about ALL the error lines. I just got the screenshot the second time.

AHK version: 1.1.29.01
Windows version: Windows 7 
![poe_macro_error](https://user-images.githubusercontent.com/40067204/41166841-8905c254-6b41-11e8-8585-015738d22eea.jpg)

**Comment by Eruyome** [comment]
You are saying that you put the macro into the documents folder, which path exactly?

**Comment by Eruyome** [comment]
`D:\Users\Eru\Documents\GitHub\POE-TradeMacro`

That's mine, I expected to get an answer like this, the exact path including the folder containing the macro files ;-)

**Comment by Tatherwood** [comment]
Yeah, that's what I wanted to give you. But when I open the Windows Explorer thing (do excuse me, my computer knowledge is limited at best), on the top side (as you can see in the picture) there's no actual path for WHERE the folder is. And on the left side, Documents comes from Libraries. They're not IN C, or D, or E, that I can see.

So... I don't know what answer to give you.
I'm ASSUMING mine would be C\Users\Tatherwood\Documents\Poe-Trade-Macro? (Cause I think the users folder is in C), but... don't quote on me that.


Still. Here's a question. I understand you're trying to help, and this information is probably important, but aren't we missing the point here?
Regardless of WHERE I unzipped the program, the actual problem is that it worked fine for a week, then stopped working, then I had to download again, then it worked okay-ish the first time, and then it stopped working again.
I don't think that's anything on MY end. Nothing changed here...

**Comment by Eruyome** [comment]
Is that windows 7?
Not quite sure but the entire path may be shown if you simply click into the address bar. Aside from that you can right click on any file/folder -> properties and see it's full path.

I can assure you that nothing changed with the macro, too. So yes it most likely is something on your end, even if you think nothing changed for you.

So, let us start of by showing me the exact path where you have your macro folder. For example, using the one you mentioned above would be wrong since that's the macros user folder which needs to be seperated form the actual macro. Well, that is if the mentioned path is `Poe-TradeMacro` instead of the one you have written `Poe-Trade-Macro`. Anyway, just give me that information first.

**Comment by Tatherwood** [comment]
Aye, as mentioned in first post, W7.
And.... yup, that helps. Showing the properties of the folder tells me C\Users\Admin\Documents, that's the path.
And there's 2 folders in there: PoE-TradeMacro & POE-TradeMacro-2.10.3.
I think one of those was created by default when running the macro for the first time, or something. cause it sure wasn't me.

**Comment by aRTy42** [comment]
The macro creates a folder in \Documents for the user settings, so that they don't get overwritten or replaced when the macro folder is overwritten by an update. That folder is called "PoE-TradeMacro".

Your folder with 2.10.3 at the end is the latest release of the macro. However, if you use the auto-updater, the macro will suggest a name without the version number so that the same macro folder name can be re-used which means that you can create a link to the macro that won't break on each update (because the path changed). That generic name is also "PoE-TradeMacro". This means the two folders will likely cause conflict.

I would advise to use something like "C:\Program Files\PoE-TradeMacro" for the macro location, or whatever location you normally use for programs. If you want to launch the macro from the Desktop for convenience (which I also do), you can then create a link to "Run_TradeMacro.ahk" and put that link on the desktop. If you then choose to overwrite the old folder when the updater asks you, that link will keep working.

**Comment by Tatherwood** [comment]
Hum... 

So, I once again deleted everything macro-related, and went to download the new version, 2.10.4. Upon running the Run_TradeMacro thing, the second folder was created: PoE-TradeMacro. Just to make sure, it didn't ask me anything. The "suggested" name you mention is automatically used. I guess I could manually change the folder name, but with your phrasing I was expecting the program to actually ask me what name I wanted to use.

Also, I think I'm missing something. The Run_Trade_Macro.ahk is ONLY in the downloaded folder, the one with 2.10.4. Which is the one that will change name with the update, right? So if I link that to desktop, I'll have issues next time it updates again, no?


Well, regardless of those two things, it seems to be working now, thank you for your help. 
It DID work perfectly fine for days before stopping working last time, though, so I'll just keep it in check, see if something else happens.

**Comment by aRTy42** [comment]
The "PoE-TradeMacro" folder in **\Documents\** is always automatically created and named that way. People should usually not need to touch the files directly there.

The folder you unzipped is the one which you can name however you want. The script will also ask about a name when the updater finds a new version. It will ask you whether you want to download, which location to download to and it allows you to overwrite your old folder.
If you name the unzipped folder you created "PoE-TradeMacro" (and not put it in documents, but rather in program files or somewhere else, like I suggested), then the updater will automatically mark that folder as a suggested location to download to (and overwrite with backup), which means the new version will take over the exact same spot the old version was in. Using links in that case is no issue, since the path of the latest version won't effectively change.

**Comment by Tatherwood** [comment]
![same problem](https://user-images.githubusercontent.com/40067204/41347589-613fdf9e-6f0a-11e8-8ce0-4234dd1e9f26.jpg)
So, once again, crap goes up.
Once more, I'm note sure if EVERY line of the problem is identical, but the "header" is. It worked fine 2 days ago, when I redownloaded. It worked fine yesterday. It's not working today.

Now, one thing I DID do was this. I wanted to leave the macro folder in documents, so I changed the Poe-TradeMacro-2.10.4 folder to "Poe-TradeMacro-changing version". (To remind myself that was the folder what would be overwritten with updates).
After changing the name, since the path had changed, I created a NEW direct link to the Run_TradeMacro.ahk. Which is the one I used to launch it today, and gave me that error.

I'm assuming whatever I did messed it up, but I don't see how.

**Comment by Eruyome** [comment]
Use this attached version, set it up like you would normalley, run it and tell me if there's a message box appearing, and show me what it says.

[POE-TradeMacro-debug.zip](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2098209/POE-TradeMacro-debug.zip)

**Comment by Tatherwood** [comment]
Well, upon launching it gave me the message on window.
![error macro](https://user-images.githubusercontent.com/40067204/41398793-c9c11a34-6fb8-11e8-8c7e-ce3f25ed60f1.jpg)

After accepting, and executing: 
![error macro](https://user-images.githubusercontent.com/40067204/41398826-e493d34c-6fb8-11e8-9c29-7a4c186b7a05.jpg)

**Comment by Tatherwood** [comment]
Ooooookay? So... After 4 days, I launched THE SAME "run macro" you gave me (the debug thing), from THE SAME folder. I didn't touch ANYTHING in these 4 days.
Now it's working again.

So yeah, I've no fricking idea what's making the macro stop working, but now I know I wasn't seeing things. As I said in my first posts, it works fine for a few days, then it stops working ON ITS OWN, because reasons... apparently for a few days too, then it works again. Amazing.

I'll update again when it stops working... again.
