### ISSUE TITLE
Error in #include file ... jsonData.ahk ... Line 2 Col 1 Char 3 ... Line #022

### ISSUE THREAD

**Issue by dsnvwlmnt** [PoE-TradeMacro/POE-TradeMacro#805]
Out of nowhere i'm getting this error now. It was working fine before and since the patch earlier on (3.4.3)...

Error in #include file ... jsonData.ahk ... Line 2 Col 1 Char 3 ... Line #022

![image](https://user-images.githubusercontent.com/14173022/45857794-57343b00-bd0f-11e8-9319-27ea179203b2.png)

**Comment by dsnvwlmnt** [comment]
No one else? How...

**Comment by aRTy42** [comment]
Is the whole `\Google Drive\` folder synced or does it have restricted access in some way? I think I remember someone having an issue with synced folders before.

**Comment by dsnvwlmnt** [comment]
Yes it's entirely synced. I've been using this setup for months with no issue. AFAIK nothing has changed...

I run PoE from 2 different computers both sourcing from the same synced macro folder.

**Comment by dsnvwlmnt** [comment]
Is this program still supported?

**Comment by aRTy42** [comment]
> Is this program still supported?
Yes, but we are only two people who maintain it as a hobby.

I'm not sure what the issue is.

Firstly, try running the macro with rightclick -> run as admin. If that does not solve it already, could you start the macro and then go to `\POE-TradeMacro\data_trade` and look at the file dates for `uniques.json` and `relics.json`. Is the day/timestamp only a few minutes old, so were those two files properly updated with the script start?
If yes, please open the `relics.json` file. It should contain only `{"relics":[]}` at the moment, is that the case for you?

If the file updating does not work, you might have an issue with connecting to Github or with write access for the macro folder. Does [uniques.json](https://raw.githubusercontent.com/PoE-TradeMacro/POE-TradeMacro/master/data_trade/uniques.json) open in the browser for you just fine? If it does, you can try moving the macro folder to test access issues. Try `C:\Program Files\PoE-TradeMacro` or something similar for example (avoid the desktop or the documents folder, those can be an issue. Since your current location is within the documents folder, that might be the reason here.)

**Comment by dsnvwlmnt** [comment]
Running as Admin gave the same error.

relics.json and uniques.json are 3 weeks old, and do not update.

Moving the folder to C:\Temp results in the same error.

I tried TakeOwnership. I tried turning off Read-Only on the folder Properties.

Same error in all cases.

**Comment by aRTy42** [comment]
Ok, I was able to reproduce the error. Your `relics.json` file has some content that should not be in there. The error message even says something about "Specifically: <" but I didn't properly pick up on that.

Please check and post that file content first, so I have an idea what might have caused it, for the future. Afterwards you can delete the `relics.json` file. If that one is missing, it should get replaced properly.

**Comment by dsnvwlmnt** [comment]
For the record i didn't touch any of the files. XML content hah! Line 1 is blank, a paste of the file is below. I also uploaded the file (renaming from relics.json to relics.json.txt to be able to upload here).


<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Backend is unhealthy</title>
  </head>
  <body>
    <h1>Error 503 Backend is unhealthy</h1>
    <p>Backend is unhealthy</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-sea1026-SEA 1537489501 2499862855</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>


[relics.json.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2466771/relics.json.txt)
