### ISSUE TITLE
[Feature] Currency Exchange rate both ways

### ISSUE THREAD

**Issue by zocke1r** [PoE-TradeMacro/POE-TradeMacro#81]
i would like to see both directions of on currency exchange rate, so from e.g chaos to fuse as well as chaos .  at least im in most cases interested in actually selling my currency for chaos instead of buying it

**Comment by Eruyome** [comment]
Yeah, that's not a bad idea, but maybe there would be more to change then. Since you can't directly buy currency via default (tooltip) search it probably doesn't matter much who is actually selling the currency, so no need for the IGN. Maybe show a history like you can see here http://poe.ninja/esc/currency (click the plus after the currency). Have to think about what is needed and what not on that tooltip.
