### ISSUE TITLE
Cant price rare items but uniques work

### ISSUE THREAD

**Issue by freddyE171** [PoE-TradeMacro/POE-TradeMacro#827]
The script runs perfectly fine, but when I want to check rare items it tells me to check the poeprices_log.
The price_log says: 

#####
#####

Request and response:
{
    "added": {
        "browserUrl": "https://www.poeprices.info/api?l=Delve&i=&w=1",
        "encodedData": "",
        "league": "Delve",
        "requestUrl": "https://www.poeprices.info/api?l=Delve&i="
    },
    "data": {},
    "error": 2,
    "status": 200
}

AHK version: AutoHotkey_1.1.26.01
Windows version: Windows 10

**Comment by Eruyome** [comment]
Yout `temp`folder should also have these files:

`base64ItemText.txt`
`itemText.txt`
`encodeToBase64.txt`

please tell me whether they exist/are emtpy. Or simply show them to me if they have contents,

**Comment by Eruyome** [comment]
https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/786#issuecomment-418206474

Try following my instructions from this comment.

**Comment by Eruyome** [comment]
No, I'm german, too.
 
TM uses the windows `certutil` tool to encode the item text to base64, which is the required format that needs to be added to the url.

I'm trying to find out what's up here but for reference here's a [google link](https://www.google.de/search?rlz=1C1CHBF_deDE807DE807&ei=0Rv4W8iFDfCNlwSp7IKADg&q=certutil+0x80070005+%28WIN32%3A+5+ERROR_ACCESS_DENIED%29&oq=certutil+0x80070005+%28WIN32%3A+5+ERROR_ACCESS_DENIED%29&gs_l=psy-ab.3...104810.107381..107828...0.0..0.85.591.9......0....1..gws-wiz.Mn8N5nMQ5cQ) if you want to take a look for yourself. I guess it can get quite complicated since you mostly find stuff regarding issues with installing certificate services on windows servers.

**Comment by Eruyome** [comment]
Btw, I'd rather look for a different solution to get this encoding done, not using certutil. I'm currently testing something written in AHK, you may have to test this in a while.

**Comment by freddyE171** [comment]
yea sure, thank you so much for taking your time fixing this I really appreciate it.

**Comment by freddyE171** [comment]
Eyy it works :D thank you so much

**Comment by Eruyome** [comment]
Nice, you're welcome.
