### ISSUE TITLE
Price checking some items causes Memory Error

### ISSUE THREAD

**Issue by jan-car** [PoE-TradeMacro/POE-TradeMacro#840]
For some items (e.g. Abyss Jewels, some uniques, rarely for rares), when trying to price check with ctrl+D "requesting search results" pops up, but nothing happens afterwards. Scrolling through tabs still works and I can change league, but price checking doesn't even pop up the info box anymore. After several minutes, this error pops up:

![capture](https://user-images.githubusercontent.com/14233291/49834871-ce70ec80-fd9d-11e8-8ef0-45913746bdbd.PNG)

I'm on Windows 10 / 64bit with AHK v1.1.30.01 and I'm using v2.12.2 of POE-TradeMacro, but this happens since a few releases (mid Delve, I think).

**Comment by Eruyome** [comment]
Can you check whether there was any windows update installed at the time where this started to happen?

**Comment by jan-car** [comment]
Yes, there were the following updates during Delve (can't say for sure when exactly the issue started happening):

October: https://support.microsoft.com/en-us/help/4462918/windows-10-update-kb4462918
November: https://support.microsoft.com/en-us/help/4467686/windows-10-update-kb4467686

Anything I have to look for?

**Comment by Eruyome** [comment]
I don't really know but you wouldn't be the first to have issues with AHK/TradeMacro because of some win10 Update, whether this is the case here I can't say.

**Comment by Eruyome** [comment]
Any update on this?Still don't really know what to test/check...

**Comment by jan-car** [comment]
It still happens (updated to the current version, but, mainly for magic items (like Abyss Jewels) and for some Gems and Uniques. If it happens, it seems to be reproducible (crashes for the same items again if I try immediately after restarting the script), so I think it does not depend on the number of items I check. Rares and their price prediction work fine all the time.

Didn't play around with the new "Curl/HTTP request timeout" option, but I assume that should not be connected to the issue, right?

If there is a log file I can provide, please let me know where I can find it.

**Comment by Eruyome** [comment]
That option is not relevant.

You said it happens with certain items, can you post their data here? ctrl +c ingame to copy that to your clipboard.

**Comment by jan-car** [comment]
I won't be able to play until tomorrow evening, I think, but I'll collect a few examples!

**Comment by Eruyome** [comment]
This seems really random to me.
Since you're pretty much the only person to report this issue I'd guess it's an issue with your system, not AHK specificially. There isn't much to find where people talk about MaxMe issues, try reading (this)[https://www.reddit.com/r/AutoHotkey/comments/5x5m33/maxmem_and_memory_leaks_discussion/] though if you want.

BUT that doesn't meant that we are completely out of options. The `#MaxMem` command
```
Sets the maximum capacity of each variable to the specified number of megabytes.
```
according to the documentation, where the default is 64 megabytes, which should be overkill already.

Try opeing `resources\ahk\TradeMacoInit.ahk` in a text editor and add the MaxMem command at the beginning:
```
#SingleInstance force
#NoEnv ; Recommended for performance and compatibility with future AutoHotkey releases.
#Persistent ; Stay open in background
#MaxMem, 128
```
should look like this. Try playing around with the value (in megabytes) and see if it helps.

**Comment by Eruyome** [comment]
Closed because the issue is so old. Feel free to message again if the issues still persist.
