### ISSUE TITLE
Fallback.exe is a trojan v2.12.2

### ISSUE THREAD

**Issue by Paccyz** [PoE-TradeMacro/POE-TradeMacro#854]
Norton 360 is deleating the fallback.exe for beeing a trojan.gen2

Why ?

**Comment by Heekzy** [comment]
Same issue. I just got it blocked by Windows Defender

**Comment by aRTy42** [comment]
Well, it is an exe file that launches several scripts, downloads updates from the web (GitHub) and reacts to keyboard input. Having the file falsely flagged is not that surprising.

You can delete the fallback.exe if you want (it is only there for people who can't launch the macro with the regular "Run_TradeMacro.ahk" file). Alternatively you can also download the "noExe" zip variant, where the exe file is not included to begin with.

**Comment by aRTy42** [comment]
The exe isn't a fixed launched file, it bundles up all the script parts that are usually initiated with the "Run_TradeMacro.ahk" file. The exe changes often because parts of the script get changed and updated. If we included an old exe, you would basically get an outdated TradeMacro version.

**Comment by Eruyome** [comment]
Starting with the next release the fallback.exe will be excluded by default and the second zip archive that can be manually downloaded will include it.

**Comment by cassianpry** [comment]
Bitdefender: POE TradeMacro\Fallback.exe file is infected with Gen: Variant.Ursu.351370 and has been moved to Quarantine. 

The owner are trying to steal my things?

**Comment by Eruyome** [comment]
Are you trolling/joking or not actually reading what's commented here?

**Comment by cassianpry** [comment]
Working only with facts and your .exe is a virus period.

**Comment by Brcrwilliams** [comment]
What an antivirus tells you is not a fact but an opinion of the AV product. They can and do get things wrong.

**Comment by Ankahra** [comment]
@cassianpry I think this is bigger than people are making it out to be? I've also had this issue with Bitdefender and since it being found on the PoE Macro folder, it is now in Windows temp folders and attempting to do things daily as shown in images below.

https://i.gyazo.com/8b5701d830c4d3306529e2a1c845e8f2.png - Initial PoE Macro one from Dec 14th.

https://i.gyazo.com/99bdf05efad41dae2d2f093f6a4c868c.png - Daily attempts since the initial one, multiple times per day.

https://i.gyazo.com/a2b6ea3011f90ba1b0b917883582861c.png - Showing it's in the Windows Temp folders.

**Comment by aRTy42** [comment]
What kind of file is it refering to in the 2nd picture? It says mostly "blocked" and only once "deleted" at the top. If windows copied something to the temp directory that bitdefender considers a malware for some reason, it's quite possible that bitdefender blocked the same thing temporarily over and over whenever there was tempfolder activity. It does not necessarily mean that file tried to do something.

As I understand it, the Fallback.exe is flagged/blocked/deleted right away when you download the script, so you never actually executed it. As I wrote before: Feel free to delete the Fallback.exe, the script does not use it (it is a backup launcher for people who have trouble with AHK and thus .ahk-files). Handle the windows temp folder however you like. You could upload the file to [virustotal](https://www.virustotal.com/#/home/upload) for better feedback or you could simply delete/quarantine it. Since the Run_TradeMacro.ahk part does not seem to cause any issues, there shouldn't be any new alerts afterwards.

Specifically about Bitdefender and Gen.Ursu I found two other occasions where GitHub projects got flagged: [here](https://github.com/Fody/Costura/issues/294) and [here](https://github.com/LibreVR/Revive/issues/858).

**Comment by Ankahra** [comment]
It's referring to the same "Gen:variant.Ursu.351370" that now appears in the Windows temp folders constantly that originally came from the Fallback.exe according to Bitdefender, even though it's been blocked and deleted a dozen times.

https://i.gyazo.com/222c4cf92f6a7e6afb45219d09dfd356.png
