### ISSUE TITLE
Additional Macros are getting overwritten with conflicts

### ISSUE THREAD

**Issue by JusKillmeQik** [PoE-TradeMacro/POE-TradeMacro#859]
Every time I restart the macro using Reload Script (use only this) the Additional Macros are reset to default values. Except one of them, which seems randomly chosen, which gets set to a value of one of the other additional macros. This obviously causes a conflict, which I fix and then restart the macro. Everything gets set to default again and another random macro gets set to a conflicting value.

AHK version: 1.1.30.00
Windows version: 10

**Comment by JusKillmeQik** [comment]
I was able to get it to stick through a single reload by modifying the file itself instead of through the gui. However, it appears when I modify the timeout for the item info it still gets reset.

**Comment by aRTy42** [comment]
That sounds like a broken file or maybe permission with the config file folder. When you say you edited the file itself, did you edit
`\Documents\PoE-TradeMacro\AdditionalMacros.ini`
or
`\<Main Script Folder>\resources\default_UserFiles\AdditionalMacros.ini`
?

The first one is the correct one to edit, the second one is downloaded with the script as a default blueprint, which is used to create the personalised file from and this default file should not be changed.

To catch multiple error sources at once, I'd recommend the following:

Go to your `\Documents\PoE-TradeMacro\` folder and delete the `AdditionalMacros.ini` file.

Manually download the latest script version from the [releases](https://github.com/PoE-TradeMacro/POE-TradeMacro/releases) page (consider using the "noExe.zip" variant since several antivirus softwares are currently falsely flagging the regular download).

Locate your main script folder (that's the folder with the "Run_TradeMacro.ahk" file) and replace it with the new download, as in: delete the current folder and afterwards extract the .zip file into a folder at the same location. (I would recommend to name the folder "POE-TradeMacro" since that's the default name that the auto-updater uses.). If you find several folders from the TradeMacro, in particular folders with the version number attached, I'd recommend to delete all those old folders and only keep the folder that you just created from the fresh download.

Launch the macro with the Run_TradeMacro.ahk file. The macro should now automatically create a new and unbroken `AdditionalMacros.ini` file at `\Documents\PoE-TradeMacro\`.

Try changing the keys now, first in the GUI and if that won't work maybe try the file again. If your `\Documents\` folder is synced to a cloud or has some special sharing function or permission restriction, that might cause issues. If that's the case report back with details.

**Comment by JusKillmeQik** [comment]
Thank you for the detailed response. The file I was editing was \Documents\PoE-TradeMacro\AdditionalMacros.ini

I was able to set everything back to default and modify it the way I needed without reinstalling everything.

However, for good measure I followed the steps you outlined and pulled everything down again. This did not over write the changes I had made to the AdditionalMacros file.

Things are working now so I am hesitant to try breaking them but if something comes up again I will be sure to let you know.

Cheers.
