### ISSUE TITLE
Trouble launching script

### ISSUE THREAD

**Issue by flortongsy** [PoE-TradeMacro/POE-TradeMacro#869]
I'm getting this message when trying to run the script.
![capture](https://user-images.githubusercontent.com/46361672/50669528-b0a93880-0f93-11e9-8afa-87492ee6d591.PNG)

**Comment by Eruyome** [comment]
Can you try not saving the macro folder to any system folder (dekstop/documents/program files)? These can cause some weird permission issues.

**Comment by flortongsy** [comment]
Now getting this message

![capture2](https://user-images.githubusercontent.com/46361672/50846793-ff612480-133d-11e9-8412-2b830a2e596d.PNG)

**Comment by Eruyome** [comment]
Have you a somewhat up to date AHK version?
1.1.x, not 1.0.x or 2.0.x

**Comment by flortongsy** [comment]
I'm running AHK version 1.1.30.01. When I try to run TradeMacroMain.ahk it's giving the same exact message.

**Comment by Eruyome** [comment]
I repeat myself, please upload your `<TM folder>\_TradeMacroMain.ahk` file.

**Comment by flortongsy** [comment]
Sorry. I'm not sure how to do that. I'm not too knowledgeable about this stuff.

**Comment by Eruyome** [comment]
Just drag and drop the file here, maybe you'll have to add it to a zip archive first.

**Comment by aRTy42** [comment]
The file is completely messed up. Parts of the code are duplicated in random locations and the error you got is because at that point some code starts in the middle of a function.

Delete the _TradeMacroMain.ahk file, launch the script with the RunTradeMacro.ahk and report back. If that gives the same error again, your source files might be broken and you might need to redownload the script, but we will see about that if it comes to it.
