### ISSUE TITLE
Trade Macro wont start since the new update 

### ISSUE THREAD

**Issue by EwzyKun** [PoE-TradeMacro/POE-TradeMacro#894]
Since the new update i cant start the trade macro 
everytime i try to start it i get this error https://gyazo.com/fe9a0c80d111c065dec514c7a591f6d7
i already tried to re-install ahk and the trade macro into a other directory
would be nice if someone could help me :D

**Comment by Eruyome** [comment]
Please upload `temp\startuplog.txt`

**Comment by EwzyKun** [comment]
[StartupLog.txt](https://github.com/PoE-TradeMacro/POE-TradeMacro/files/2752595/StartupLog.txt)

**Comment by EwzyKun** [comment]
Yea i need to check the captcha aswell everytime

**Comment by Schlangenbob** [comment]
As far as I could gather from the webz it either is a contamination with maleware that makes you get this captcha side (which i checked with mbam - nothing found) or it is due to your router providing changing IP's to you (which most routers do). Take all of that with a grain of salt since I am not that knowledgable about anything software.

**Comment by EwzyKun** [comment]
it works for me now too. Thanks for your help :D
