### ISSUE TITLE
Someone can hel with?

### ISSUE THREAD

**Issue by zolw9** [PoE-TradeMacro/POE-TradeMacro#925]
_TEMPLATE_ (Remove the explanations here from your post) 

Make sure:
* That you have checked the Wiki/FAQ before creating any issue.
* That poe.trade/GGG's website don't have any issues if loading the script takes too long or failes.

Information to include:
* AHK (including 32/64bit) version if you have any kind of script errors.
* Windows version could be relevant.

Fill out everything that may be relevant and remove everything except these informations below:  

AHK version:
Windows version:

Problem witch PoE Trade Macro.

https://imgur.com/2hTBZ01

**Comment by Eruyome** [comment]
If you still have this issue please delete the folder `%userprofile%\poe-trademacro\custommacros` and try again.

**Comment by zolw9** [comment]
i dont have a this folde.

**Comment by Eruyome** [comment]
My bad, it's `%userprofile%\Documents\poe-trademacro\custommacros`

**Comment by zolw9** [comment]
i still no have this folder.

**Comment by Eruyome** [comment]
Ok, so there are two things to clarify.

- My comment should have been the solution to your other issue here https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/924
- `%userprofile%` is a placeholder for your systems user profile location and the specified folder should be there BUT I won't insist on that since your error message from this issue here shows some file write permission issues.

Have you checked, as suggested in the error messsage, whether your security suite/antivir or any other application blocks AHK?
