### ISSUE TITLE
merge_Trademacro error

### ISSUE THREAD

**Issue by onewideboy** [PoE-TradeMacro/POE-TradeMacro#967]
AHK version: 1.1.30.03 (64-bit)
Windows version: 10

![image](https://user-images.githubusercontent.com/49958777/56684403-f703de00-66cf-11e9-907e-3412a355af60.png)

i've tried removing and downloading the full zip twice but it still didn't work.

thank you in advance.

**Comment by Eruyome** [comment]
Sorry for the very late answer, if you're still experiencing this issue please check whether the file in that error message actually exists or not.

**Comment by Snarkie** [comment]
I have the same issue. 
Win 10, 64 bit
AHK v1.1.30.03

To reproduce on my end, all I need to do is:
- Unpack TradeMacro 2.14.2
- Start Run_TradeMacro.ahk

Startup screen shows, then trademacro icon shows for a couple of seconds, then trademacro terminates. Tried it multiple times with one of 2 results: 
- Either Merge_TradeMacro.ahk is deleted, and the next attempt to use Run_TradeMacro.ahk fails with the above error message. 
- Or Merge_TradeMacro is deleted and Run_TradeMacro is deleted as well, leaving _TradeMacroMain.ahk in the main folder. 

In either case, unpacking from archive again doesn't restore the files, but fails with an access denied message. I have to unpack to a different folder. I cannot create or move files of the same name as the deleted files in the same locations.

Even more bizarre: When first encountering this, I started trademacro from a batch script in conjunction with other macros and poe. It deleted the batch script file and other started macros as well, and doesn't allow creating new files of the same name in those locations as well. This may or may not be related, and trademacro might not be the cause of this, but since just starting trademacro by itself caused similar issues, it seemed worth mentioning.

**Comment by Eruyome** [comment]
There where some recent issues with antivir software blocking/removing TM files, sometimes with very persistent behaviour (making folder exceptions not sufficient, requiring file exceptions). 

https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/943

https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/945

https://github.com/PoE-TradeMacro/POE-TradeMacro/issues/946

**Comment by Snarkie** [comment]
I do use Avast, however my notifications, logs and quarantine folder do not indicate any activity on that front at all.

**Comment by Eruyome** [comment]
I can't really think of any other reason for files "going missing" than antivirus software. I don't know whether Avast can interfere here without you seeing it in the logs, never used it. But I also wouldn't be surprised.

**Comment by mpcrawf** [comment]
I ran into this same issue.  I am running Avast Antivirus.  Extracting the folder results in a permissions issue on Merge_TradeMacro.ahk.  I was able to solve my problem by turning off Avast's shields temporarily and re-extracting.
