### ISSUE TITLE
Sceptre treated as one handed mace

### ISSUE THREAD

**Issue by terbenstaar** [PoE-TradeMacro/POE-TradeMacro#973]
Some of the cceptres are treated as one handed mace when using item search (ctrl-alt-D or ctrl Q)
for example: Tyrant's Sekhem.

**Comment by subsetdht** [comment]
Sceptres are a subset of Maces.
https://pathofexile.gamepedia.com/Tyrant%27s_Sekhem

Tyrant's Sekhem is a One Handed mace

**Comment by terbenstaar** [comment]
so is Carnal Sceptre, but macro will search it as sceptre from trade sites, instead one handed mace as it does with Tyrant's Sekhem

**Comment by subsetdht** [comment]
Ah - understood.

Which version of POE TradeMacro do you presently have installed?
There were two fixes that went in 2.7.7 and 2.10.5 that address the issue. Maybe this is related to the temp leagues.

2.7.7 resolved down to Sceptre instead of 1h Mace.
2.10.5 updated the type classes for items, specifically Tyrant's Sekhem was updated.  

If you look at the data_trade\item_bases_weapon.json you can see that Tyrant's and Carnal are both set to Sceptre base type.

**Comment by terbenstaar** [comment]
2.14.1 version

**Comment by Eruyome** [comment]
Fixed in the upcoming version.
