### ISSUE TITLE
Using any macro like f3 or f5, makes my ctrl key be considered pressed. So when I try opening my inventory for example, it does a ctrl+I command instead.

### ISSUE THREAD

**Issue by nagazai** [PoE-TradeMacro/POE-TradeMacro#980]
AHK version: 1.1.30 (I suppose its 64bits, couldnt find where it says)
Windows version: 10 PRO

Like said on title. I press Ctrl+D for a price check, now my Ctrl is considered being pressed. I thought it was a keyboard problem, but then if I use any of the F commands, after that, Ctrl is considered pushed. I cannot use potions or open inventory because it does the commands. I could remove every command that uses ctrl but that would be pointless.

**Comment by Eruyome** [comment]
F5 (Hideout) does the following:

```
SendInput {Enter}/hideout{Enter}{Enter}{Up}{Up}{Esc}	
```
There's not ctrl, shift or anything similiar involved here.

ctrl + d does:
```
Send ^{%scancode_c%}
```
which is the same as 
```
Send ^c
```
so, "send ctrl + c". Sending ctrl does not leave the key "UP" though. There are commands for that `{Ctrl Down} {Ctrl Up}`.

If you start the macro -> press f5 without doing anything else and ctrl is considered UP then my first guess would be that it's not related to the macro. Which would make some sense since nobody else seems to have this issue.

If you open `<tm folder>\resources\ahk\trademacro.ahk` in a text editor, look for `Send ^{%scancode_c%}` at line 23 and change it to `Send ^{%scancode_c%}{Ctrl Up}` and it fixes your issue, then that would be good to know and may be implemented just in case, but it should still be caused by something else.

**Comment by nagazai** [comment]
good to know it's not an overall problem and thanks for the solution. I don't know why that happens, but if I discover, I come back to tell you even if it's not the script. 
thanks for everything

**Comment by Eruyome** [comment]
If adding the `{Ctrl Up}` works thats nice but it would only be an annoying solution if you add it yourself since every script update would revert it.

Make sure to check whether this solves your issues and I can consider adding it to make sure that such issues don't ahppen for anyone else in the future.

**Comment by nagazai** [comment]
> If adding the `{Ctrl Up}` works thats nice but it would only be an annoying solution if you add it yourself since every script update would revert it.
> 
> Make sure to check whether this solves your issues and I can consider adding it to make sure that such issues don't ahppen for anyone else in the future.

Don't about it anymore. I noticed that the problem is another macro. 
Using a logout macro, which has a f5 for hideout and f3 for reamining mobs for example, for some weird reason, lock down the ctrl button for this macro until it is pressed. It does not consider as pressed for himself. 
Example: If I press f3 (monster remaning), then press 1, I use a potion. But if I press "i" to open my inventory, I open poe.trade search window. Because Ctrl+1 is a macro from my logout macro, but Ctrl+i is a macro from this TradeMacro. So the problem is that, my logout macro is only making Ctrl seem pressed to the TradeMacro. Not even to itself. So I cannot use both macros at the same time. 

If I have only the TradeMacro, I can use any hotkey and Ctrl won't be considered pressed. If I use only the logout macro, Ctrl won't be considered pressed. If I use both macros, and use any hotkey from the Logout macro, Ctrl will be considered pressed for any command from the TradeMacro. 

So... yea. what I will do is remove every command from the trade macro beside logout, then use only the TradeMacro. But it's clearly a problem with my PC, so don't bother with this post anymore. Thanks for all the help

**Comment by Eruyome** [comment]
Are you using Lutbots logout macro by chance? If that's the case open the TradeMacro settings and take a look at the lutbot tab and use the lutbot light version.
