### ISSUE TITLE
Q> is this from TMC or my pc get virus ?

### ISSUE THREAD

**Issue by dekspyware** [PoE-TradeMacro/POE-TradeMacro#998]
it never happens before. so i think my pc just got virus ?
but just asking for make it sure is it from tmc or not.
![virus](https://user-images.githubusercontent.com/10884065/59892635-20a56100-9404-11e9-8b29-2933eb31d33e.png)

**Comment by Eruyome** [comment]
Not sure which file is referenced here but the description "this program ... downloads oder programs" doesn't mean much since that's what TradeMacro does, downloading stuff.

Anyways, read the FAQ https://github.com/POE-TradeMacro/POE-TradeMacro/wiki/FAQ#23-trademacro-or-some-files-being-reported-to-be-maliciousa-virus

**Comment by aRTy42** [comment]
To my knowledge FzD.exe does **not** belong to the TradeMacro and the filepath is **not** TradeMacro's main path.
Consider the file as a Trojan unless you find something clearly exculpatory. If you want to check it against further malware tests, try [virustotal.com](https://www.virustotal.com).
